package provider

// Note:  This file is automatically generated.  Manually made changes
// will be overwritten when the provider is generated.

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/PaloAltoNetworks/pango"
	"github.com/PaloAltoNetworks/pango/device/administrator"
	pangoutil "github.com/PaloAltoNetworks/pango/util"

	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	rsschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	sdkmanager "github.com/PaloAltoNetworks/terraform-provider-panos/internal/manager"
)

// Generate Terraform Data Source object.
var (
	_ datasource.DataSource              = &AdministratorDataSource{}
	_ datasource.DataSourceWithConfigure = &AdministratorDataSource{}
)

func NewAdministratorDataSource() datasource.DataSource {
	return &AdministratorDataSource{}
}

type AdministratorDataSource struct {
	client  *pango.Client
	manager *sdkmanager.EntryObjectManager[*administrator.Entry, administrator.Location, *administrator.Service]
}

type AdministratorDataSourceFilter struct {
	// TODO: Generate Data Source filter via function
}

type AdministratorDataSourceModel struct {
	Location              types.Object `tfsdk:"location"`
	Name                  types.String `tfsdk:"name"`
	AuthenticationProfile types.String `tfsdk:"authentication_profile"`
	PublicKey             types.String `tfsdk:"public_key"`
	Password              types.String `tfsdk:"password"`
	Permissions           types.Object `tfsdk:"permissions"`
}
type AdministratorDataSourcePermissionsObject struct {
	RoleBased types.Object `tfsdk:"role_based"`
}
type AdministratorDataSourcePermissionsRoleBasedObject struct {
	Superuser    types.Bool   `tfsdk:"superuser"`
	Superreader  types.Bool   `tfsdk:"superreader"`
	Deviceadmin  types.Bool   `tfsdk:"deviceadmin"`
	Devicereader types.Bool   `tfsdk:"devicereader"`
	Vsysadmin    types.Bool   `tfsdk:"vsysadmin"`
	Vsysreader   types.Bool   `tfsdk:"vsysreader"`
	Custom       types.Object `tfsdk:"custom"`
}
type AdministratorDataSourcePermissionsRoleBasedCustomObject struct {
	Profile types.String `tfsdk:"profile"`
}

func (o *AdministratorDataSourceModel) AttributeTypes() map[string]attr.Type {

	var locationObj AdministratorLocation

	var permissionsObj *AdministratorDataSourcePermissionsObject
	return map[string]attr.Type{
		"location": types.ObjectType{
			AttrTypes: locationObj.AttributeTypes(),
		},
		"name":                   types.StringType,
		"authentication_profile": types.StringType,
		"public_key":             types.StringType,
		"password":               types.StringType,
		"permissions": types.ObjectType{
			AttrTypes: permissionsObj.AttributeTypes(),
		},
	}
}

func (o AdministratorDataSourceModel) AncestorName() string {
	return ""
}

func (o AdministratorDataSourceModel) EntryName() *string {
	return nil
}
func (o *AdministratorDataSourcePermissionsObject) AttributeTypes() map[string]attr.Type {

	var roleBasedObj *AdministratorDataSourcePermissionsRoleBasedObject
	return map[string]attr.Type{
		"role_based": types.ObjectType{
			AttrTypes: roleBasedObj.AttributeTypes(),
		},
	}
}

func (o AdministratorDataSourcePermissionsObject) AncestorName() string {
	return "permissions"
}

func (o AdministratorDataSourcePermissionsObject) EntryName() *string {
	return nil
}
func (o *AdministratorDataSourcePermissionsRoleBasedObject) AttributeTypes() map[string]attr.Type {

	var customObj *AdministratorDataSourcePermissionsRoleBasedCustomObject
	return map[string]attr.Type{
		"superuser":    types.BoolType,
		"superreader":  types.BoolType,
		"deviceadmin":  types.BoolType,
		"devicereader": types.BoolType,
		"vsysadmin":    types.BoolType,
		"vsysreader":   types.BoolType,
		"custom": types.ObjectType{
			AttrTypes: customObj.AttributeTypes(),
		},
	}
}

func (o AdministratorDataSourcePermissionsRoleBasedObject) AncestorName() string {
	return "role-based"
}

func (o AdministratorDataSourcePermissionsRoleBasedObject) EntryName() *string {
	return nil
}
func (o *AdministratorDataSourcePermissionsRoleBasedCustomObject) AttributeTypes() map[string]attr.Type {

	return map[string]attr.Type{
		"profile": types.StringType,
	}
}

func (o AdministratorDataSourcePermissionsRoleBasedCustomObject) AncestorName() string {
	return "custom"
}

func (o AdministratorDataSourcePermissionsRoleBasedCustomObject) EntryName() *string {
	return nil
}

func (o *AdministratorDataSourceModel) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **administrator.Entry, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	authenticationProfile_value := o.AuthenticationProfile.ValueStringPointer()
	publicKey_value := o.PublicKey.ValueStringPointer()

	var password_value *string
	{
		valueKey, err := CreateXpathForAttributeWithAncestors(ancestors, "password")
		if err != nil {
			diags.AddError("Failed to create encrypted values state key", err.Error())
			return diags
		}
		err = ev.StorePlaintextValue(valueKey, "solo", o.Password.ValueString())
		if err != nil {
			diags.AddError("Failed to manage encrypted values state", err.Error())
			return diags
		}
		password_value = o.Password.ValueStringPointer()
	}
	var permissions_entry *administrator.Permissions
	if !o.Permissions.IsUnknown() && !o.Permissions.IsNull() {
		if *obj != nil && (*obj).Permissions != nil {
			permissions_entry = (*obj).Permissions
		} else {
			permissions_entry = new(administrator.Permissions)
		}
		var object *AdministratorDataSourcePermissionsObject
		diags.Append(o.Permissions.As(ctx, &object, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
		diags.Append(object.CopyToPango(ctx, client, ancestors, &permissions_entry, ev)...)
		if diags.HasError() {
			return diags
		}
	}

	if (*obj) == nil {
		*obj = new(administrator.Entry)
	}
	(*obj).Name = o.Name.ValueString()
	(*obj).AuthenticationProfile = authenticationProfile_value
	(*obj).PublicKey = publicKey_value
	(*obj).Phash = password_value
	(*obj).Permissions = permissions_entry

	return diags
}
func (o *AdministratorDataSourcePermissionsObject) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **administrator.Permissions, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	var roleBased_entry *administrator.PermissionsRoleBased
	if !o.RoleBased.IsUnknown() && !o.RoleBased.IsNull() {
		if *obj != nil && (*obj).RoleBased != nil {
			roleBased_entry = (*obj).RoleBased
		} else {
			roleBased_entry = new(administrator.PermissionsRoleBased)
		}
		var object *AdministratorDataSourcePermissionsRoleBasedObject
		diags.Append(o.RoleBased.As(ctx, &object, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
		diags.Append(object.CopyToPango(ctx, client, append(ancestors, o), &roleBased_entry, ev)...)
		if diags.HasError() {
			return diags
		}
	}

	if (*obj) == nil {
		*obj = new(administrator.Permissions)
	}
	(*obj).RoleBased = roleBased_entry

	return diags
}
func (o *AdministratorDataSourcePermissionsRoleBasedObject) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **administrator.PermissionsRoleBased, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	superuser_value := o.Superuser.ValueBoolPointer()
	superreader_value := o.Superreader.ValueBoolPointer()
	deviceadmin_value := o.Deviceadmin.ValueBoolPointer()
	devicereader_value := o.Devicereader.ValueBoolPointer()
	vsysadmin_value := o.Vsysadmin.ValueBoolPointer()
	vsysreader_value := o.Vsysreader.ValueBoolPointer()
	var custom_entry *administrator.PermissionsRoleBasedCustom
	if !o.Custom.IsUnknown() && !o.Custom.IsNull() {
		if *obj != nil && (*obj).Custom != nil {
			custom_entry = (*obj).Custom
		} else {
			custom_entry = new(administrator.PermissionsRoleBasedCustom)
		}
		var object *AdministratorDataSourcePermissionsRoleBasedCustomObject
		diags.Append(o.Custom.As(ctx, &object, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
		diags.Append(object.CopyToPango(ctx, client, append(ancestors, o), &custom_entry, ev)...)
		if diags.HasError() {
			return diags
		}
	}

	if (*obj) == nil {
		*obj = new(administrator.PermissionsRoleBased)
	}
	(*obj).Superuser = superuser_value
	(*obj).Superreader = superreader_value
	(*obj).Deviceadmin = deviceadmin_value
	(*obj).Devicereader = devicereader_value
	(*obj).Vsysadmin = vsysadmin_value
	(*obj).Vsysreader = vsysreader_value
	(*obj).Custom = custom_entry

	return diags
}
func (o *AdministratorDataSourcePermissionsRoleBasedCustomObject) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **administrator.PermissionsRoleBasedCustom, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	profile_value := o.Profile.ValueStringPointer()

	if (*obj) == nil {
		*obj = new(administrator.PermissionsRoleBasedCustom)
	}
	(*obj).Profile = profile_value

	return diags
}

func (o *AdministratorDataSourceModel) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *administrator.Entry, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics

	var permissions_obj *AdministratorDataSourcePermissionsObject
	if o.Permissions.IsNull() {
		permissions_obj = new(AdministratorDataSourcePermissionsObject)
	} else {
		diags.Append(o.Permissions.As(ctx, &permissions_obj, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
	}
	permissions_object := types.ObjectNull(permissions_obj.AttributeTypes())
	if obj.Permissions != nil {
		diags.Append(permissions_obj.CopyFromPango(ctx, client, ancestors, obj.Permissions, ev)...)
		if diags.HasError() {
			return diags
		}
		var diags_tmp diag.Diagnostics
		permissions_object, diags_tmp = types.ObjectValueFrom(ctx, permissions_obj.AttributeTypes(), permissions_obj)
		diags.Append(diags_tmp...)
		if diags.HasError() {
			return diags
		}
	}

	var authenticationProfile_value types.String
	if obj.AuthenticationProfile != nil {
		authenticationProfile_value = types.StringValue(*obj.AuthenticationProfile)
	}
	var publicKey_value types.String
	if obj.PublicKey != nil {
		publicKey_value = types.StringValue(*obj.PublicKey)
	}
	var password_value types.String
	if obj.Phash != nil {
		valueKey, err := CreateXpathForAttributeWithAncestors(ancestors, "password")
		if err != nil {
			diags.AddError("Failed to create encrypted values state key", err.Error())
			return diags
		}

		if evFromState, found := ev.GetEncryptedValue(valueKey); found && ev.PreferServerState() && *obj.Phash != evFromState {
			password_value = types.StringPointerValue(obj.Phash)
		} else if value, found := ev.GetPlaintextValue(valueKey); found {
			password_value = types.StringValue(value)
		} else {
			diags.AddWarning("Failed to read plaintext value from encrypted state, fallback value used", fmt.Sprintf("Missing plaintext value for %s", valueKey))
			password_value = types.StringValue("[PLAINTEXT-VALUE-MISSING]")
		}

		if !ev.PreferServerState() {
			err = ev.StoreEncryptedValue(valueKey, "solo", *obj.Phash)
			if err != nil {
				diags.AddError("Failed to store encrypted values state", err.Error())
				return diags
			}
		}
	}
	o.Name = types.StringValue(obj.Name)
	o.AuthenticationProfile = authenticationProfile_value
	o.PublicKey = publicKey_value
	o.Password = password_value
	o.Permissions = permissions_object

	return diags
}

func (o *AdministratorDataSourcePermissionsObject) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *administrator.Permissions, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics

	var roleBased_obj *AdministratorDataSourcePermissionsRoleBasedObject
	if o.RoleBased.IsNull() {
		roleBased_obj = new(AdministratorDataSourcePermissionsRoleBasedObject)
	} else {
		diags.Append(o.RoleBased.As(ctx, &roleBased_obj, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
	}
	roleBased_object := types.ObjectNull(roleBased_obj.AttributeTypes())
	if obj.RoleBased != nil {
		diags.Append(roleBased_obj.CopyFromPango(ctx, client, append(ancestors, o), obj.RoleBased, ev)...)
		if diags.HasError() {
			return diags
		}
		var diags_tmp diag.Diagnostics
		roleBased_object, diags_tmp = types.ObjectValueFrom(ctx, roleBased_obj.AttributeTypes(), roleBased_obj)
		diags.Append(diags_tmp...)
		if diags.HasError() {
			return diags
		}
	}

	o.RoleBased = roleBased_object

	return diags
}

func (o *AdministratorDataSourcePermissionsRoleBasedObject) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *administrator.PermissionsRoleBased, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics

	var custom_obj *AdministratorDataSourcePermissionsRoleBasedCustomObject
	if o.Custom.IsNull() {
		custom_obj = new(AdministratorDataSourcePermissionsRoleBasedCustomObject)
	} else {
		diags.Append(o.Custom.As(ctx, &custom_obj, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
	}
	custom_object := types.ObjectNull(custom_obj.AttributeTypes())
	if obj.Custom != nil {
		diags.Append(custom_obj.CopyFromPango(ctx, client, append(ancestors, o), obj.Custom, ev)...)
		if diags.HasError() {
			return diags
		}
		var diags_tmp diag.Diagnostics
		custom_object, diags_tmp = types.ObjectValueFrom(ctx, custom_obj.AttributeTypes(), custom_obj)
		diags.Append(diags_tmp...)
		if diags.HasError() {
			return diags
		}
	}

	var superuser_value types.Bool
	if obj.Superuser != nil {
		superuser_value = types.BoolValue(*obj.Superuser)
	}
	var superreader_value types.Bool
	if obj.Superreader != nil {
		superreader_value = types.BoolValue(*obj.Superreader)
	}
	var deviceadmin_value types.Bool
	if obj.Deviceadmin != nil {
		deviceadmin_value = types.BoolValue(*obj.Deviceadmin)
	}
	var devicereader_value types.Bool
	if obj.Devicereader != nil {
		devicereader_value = types.BoolValue(*obj.Devicereader)
	}
	var vsysadmin_value types.Bool
	if obj.Vsysadmin != nil {
		vsysadmin_value = types.BoolValue(*obj.Vsysadmin)
	}
	var vsysreader_value types.Bool
	if obj.Vsysreader != nil {
		vsysreader_value = types.BoolValue(*obj.Vsysreader)
	}
	o.Superuser = superuser_value
	o.Superreader = superreader_value
	o.Deviceadmin = deviceadmin_value
	o.Devicereader = devicereader_value
	o.Vsysadmin = vsysadmin_value
	o.Vsysreader = vsysreader_value
	o.Custom = custom_object

	return diags
}

func (o *AdministratorDataSourcePermissionsRoleBasedCustomObject) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *administrator.PermissionsRoleBasedCustom, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics

	var profile_value types.String
	if obj.Profile != nil {
		profile_value = types.StringValue(*obj.Profile)
	}
	o.Profile = profile_value

	return diags
}

func (o *AdministratorDataSourceModel) resourceXpathParentComponents() ([]string, error) {
	var components []string
	return components, nil
}

func AdministratorDataSourceSchema() dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{

			"location": AdministratorDataSourceLocationSchema(),

			"name": dsschema.StringAttribute{
				Description: "",
				Required:    true,
			},

			"authentication_profile": dsschema.StringAttribute{
				Description: "Authentication profile for this administrator",
				Optional:    true,
				Computed:    true,
			},

			"public_key": dsschema.StringAttribute{
				Description: "SSH public key for certificate-based authentication",
				Optional:    true,
				Computed:    true,
			},

			"password": dsschema.StringAttribute{
				Description: "Hashed administrator password",
				Optional:    true,
				Computed:    true,
				Sensitive:   true,
			},

			"permissions": AdministratorDataSourcePermissionsSchema(),
		},
	}
}

func (o *AdministratorDataSourceModel) getTypeFor(name string) attr.Type {
	schema := AdministratorDataSourceSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case dsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case dsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func AdministratorDataSourcePermissionsSchema() dsschema.SingleNestedAttribute {
	return dsschema.SingleNestedAttribute{
		Description: "",
		Optional:    true,
		Computed:    true,
		Attributes: map[string]dsschema.Attribute{

			"role_based": AdministratorDataSourcePermissionsRoleBasedSchema(),
		},
	}
}

func (o *AdministratorDataSourcePermissionsObject) getTypeFor(name string) attr.Type {
	schema := AdministratorDataSourcePermissionsSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case dsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case dsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func AdministratorDataSourcePermissionsRoleBasedSchema() dsschema.SingleNestedAttribute {
	return dsschema.SingleNestedAttribute{
		Description: "",
		Optional:    true,
		Computed:    true,
		Attributes: map[string]dsschema.Attribute{

			"superuser": dsschema.BoolAttribute{
				Description: "Full system access",
				Optional:    true,
				Computed:    true,
			},

			"superreader": dsschema.BoolAttribute{
				Description: "Read-only access to entire system",
				Optional:    true,
				Computed:    true,
			},

			"deviceadmin": dsschema.BoolAttribute{
				Description: "Device administrator access (all vsys)",
				Optional:    true,
				Computed:    true,
			},

			"devicereader": dsschema.BoolAttribute{
				Description: "Device read-only access (all vsys)",
				Optional:    true,
				Computed:    true,
			},

			"vsysadmin": dsschema.BoolAttribute{
				Description: "Virtual system administrator access",
				Optional:    true,
				Computed:    true,
			},

			"vsysreader": dsschema.BoolAttribute{
				Description: "Virtual system read-only access",
				Optional:    true,
				Computed:    true,
			},

			"custom": AdministratorDataSourcePermissionsRoleBasedCustomSchema(),
		},
	}
}

func (o *AdministratorDataSourcePermissionsRoleBasedObject) getTypeFor(name string) attr.Type {
	schema := AdministratorDataSourcePermissionsRoleBasedSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case dsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case dsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func AdministratorDataSourcePermissionsRoleBasedCustomSchema() dsschema.SingleNestedAttribute {
	return dsschema.SingleNestedAttribute{
		Description: "",
		Optional:    true,
		Computed:    true,
		Attributes: map[string]dsschema.Attribute{

			"profile": dsschema.StringAttribute{
				Description: "Custom admin role profile name",
				Optional:    true,
				Computed:    true,
			},
		},
	}
}

func (o *AdministratorDataSourcePermissionsRoleBasedCustomObject) getTypeFor(name string) attr.Type {
	schema := AdministratorDataSourcePermissionsRoleBasedCustomSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case dsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case dsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func AdministratorDataSourceLocationSchema() rsschema.Attribute {
	return AdministratorLocationSchema()
}

// Metadata returns the data source type name.
func (d *AdministratorDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_administrator"
}

// Schema defines the schema for this data source.
func (d *AdministratorDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = AdministratorDataSourceSchema()
}

// Configure prepares the struct.
func (d *AdministratorDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	providerData := req.ProviderData.(*ProviderData)
	d.client = providerData.Client
	specifier, _, err := administrator.Versioning(d.client.Versioning())
	if err != nil {
		resp.Diagnostics.AddError("Failed to configure SDK client", err.Error())
		return
	}
	batchSize := providerData.MultiConfigBatchSize
	d.manager = sdkmanager.NewEntryObjectManager[*administrator.Entry, administrator.Location, *administrator.Service](d.client, administrator.NewService(d.client), batchSize, specifier, administrator.SpecMatches)
}
func (o *AdministratorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {

	var state AdministratorDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var encryptedValues []byte
	ev, err := NewEncryptedValuesManager(encryptedValues, true)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read encrypted values from private state", err.Error())
		return
	}

	var location administrator.Location

	{
		var terraformLocation AdministratorLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Panorama.IsNull() {
			location.Panorama = &administrator.PanoramaLocation{}
			var innerLocation AdministratorPanoramaLocation
			resp.Diagnostics.Append(terraformLocation.Panorama.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.Template.IsNull() {
			location.Template = &administrator.TemplateLocation{}
			var innerLocation AdministratorTemplateLocation
			resp.Diagnostics.Append(terraformLocation.Template.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Template.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.Template.Template = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateStack.IsNull() {
			location.TemplateStack = &administrator.TemplateStackLocation{}
			var innerLocation AdministratorTemplateStackLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStack.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStack.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStack.TemplateStack = innerLocation.Name.ValueString()
		}
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource read", map[string]any{
		"resource_name": "panos_administrator_resource",
		"function":      "Read",
		"name":          state.Name.ValueString(),
	})

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}
	object, err := o.manager.Read(ctx, location, components, state.Name.ValueString())
	if err != nil {
		if errors.Is(err, sdkmanager.ErrObjectNotFound) {
			resp.Diagnostics.AddError("Error reading data", err.Error())
		} else {
			resp.Diagnostics.AddError("Error reading entry", err.Error())
		}
		return
	}

	copy_diags := state.CopyFromPango(ctx, o.client, nil, object, ev)
	resp.Diagnostics.Append(copy_diags...)

	/*
			// Keep the timeouts.
		    // TODO: This won't work for state import.
			state.Timeouts = state.Timeouts
	*/

	state.Location = state.Location

	// Done.
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)

}

// Generate Terraform Resource object
var (
	_ resource.Resource                = &AdministratorResource{}
	_ resource.ResourceWithConfigure   = &AdministratorResource{}
	_ resource.ResourceWithImportState = &AdministratorResource{}
)

func NewAdministratorResource() resource.Resource {
	if _, found := resourceFuncMap["panos_administrator"]; !found {
		resourceFuncMap["panos_administrator"] = resourceFuncs{
			CreateImportId: AdministratorImportStateCreator,
		}
	}
	return &AdministratorResource{}
}

type AdministratorResource struct {
	client  *pango.Client
	manager *sdkmanager.EntryObjectManager[*administrator.Entry, administrator.Location, *administrator.Service]
}

func AdministratorResourceLocationSchema() rsschema.Attribute {
	return AdministratorLocationSchema()
}

type AdministratorResourceModel struct {
	Location              types.Object `tfsdk:"location"`
	Name                  types.String `tfsdk:"name"`
	AuthenticationProfile types.String `tfsdk:"authentication_profile"`
	PublicKey             types.String `tfsdk:"public_key"`
	Password              types.String `tfsdk:"password"`
	Permissions           types.Object `tfsdk:"permissions"`
}
type AdministratorResourcePermissionsObject struct {
	RoleBased types.Object `tfsdk:"role_based"`
}
type AdministratorResourcePermissionsRoleBasedObject struct {
	Superuser    types.Bool   `tfsdk:"superuser"`
	Superreader  types.Bool   `tfsdk:"superreader"`
	Deviceadmin  types.Bool   `tfsdk:"deviceadmin"`
	Devicereader types.Bool   `tfsdk:"devicereader"`
	Vsysadmin    types.Bool   `tfsdk:"vsysadmin"`
	Vsysreader   types.Bool   `tfsdk:"vsysreader"`
	Custom       types.Object `tfsdk:"custom"`
}
type AdministratorResourcePermissionsRoleBasedCustomObject struct {
	Profile types.String `tfsdk:"profile"`
}

func (o *AdministratorResourceModel) ValidateConfig(ctx context.Context, resp *resource.ValidateConfigResponse, path path.Path) {
	if !o.Password.IsUnknown() && !o.Password.IsNull() {
		value := o.Password.ValueString()
		if strings.Contains(value, "[PLAINTEXT-VALUE-MISSING]") {
			resp.Diagnostics.AddAttributeError(
				path.AtName("password"),
				"Invalid Encrypted/Hashed Field Value",
				fmt.Sprintf("The attribute at path %s contains the placeholder value '[PLAINTEXT-VALUE-MISSING]'. This value is likely from an import operation. The provider cannot decrypt encrypted/hashed values from the device during import. Please provide a valid plaintext value.", path.AtName("password").String()),
			)
		}
	}
	if !o.Permissions.IsUnknown() && !o.Permissions.IsNull() {
		var nestedObj AdministratorResourcePermissionsObject
		diags := o.Permissions.As(ctx, &nestedObj, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			resp.Diagnostics.Append(diags...)
		} else {
			nestedObj.ValidateConfig(ctx, resp, path.AtName("permissions"))
		}
	}
}

func (o *AdministratorResourcePermissionsObject) ValidateConfig(ctx context.Context, resp *resource.ValidateConfigResponse, path path.Path) {
	if !o.RoleBased.IsUnknown() && !o.RoleBased.IsNull() {
		var nestedObj AdministratorResourcePermissionsRoleBasedObject
		diags := o.RoleBased.As(ctx, &nestedObj, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			resp.Diagnostics.Append(diags...)
		} else {
			nestedObj.ValidateConfig(ctx, resp, path.AtName("role_based"))
		}
	}
}

func (o *AdministratorResourcePermissionsRoleBasedObject) ValidateConfig(ctx context.Context, resp *resource.ValidateConfigResponse, path path.Path) {
	if !o.Custom.IsUnknown() && !o.Custom.IsNull() {
		var nestedObj AdministratorResourcePermissionsRoleBasedCustomObject
		diags := o.Custom.As(ctx, &nestedObj, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			resp.Diagnostics.Append(diags...)
		} else {
			nestedObj.ValidateConfig(ctx, resp, path.AtName("custom"))
		}
	}
}

func (o *AdministratorResourcePermissionsRoleBasedCustomObject) ValidateConfig(ctx context.Context, resp *resource.ValidateConfigResponse, path path.Path) {
}

func (o *AdministratorResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {

	var resource AdministratorResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &resource)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resource.ValidateConfig(ctx, resp, path.Empty())
}

// <ResourceSchema>

func AdministratorResourceSchema() rsschema.Schema {
	return rsschema.Schema{
		Attributes: map[string]rsschema.Attribute{

			"location": AdministratorResourceLocationSchema(),

			"name": rsschema.StringAttribute{
				Description: "",
				Required:    true,
			},

			"authentication_profile": rsschema.StringAttribute{
				Description: "Authentication profile for this administrator",
				Optional:    true,
			},

			"public_key": rsschema.StringAttribute{
				Description: "SSH public key for certificate-based authentication",
				Optional:    true,
			},

			"password": rsschema.StringAttribute{
				Description: "Hashed administrator password",
				Optional:    true,
				Sensitive:   true,
			},

			"permissions": AdministratorResourcePermissionsSchema(),
		},
	}
}

func (o *AdministratorResourceModel) getTypeFor(name string) attr.Type {
	schema := AdministratorResourceSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case rsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case rsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func AdministratorResourcePermissionsSchema() rsschema.SingleNestedAttribute {
	return rsschema.SingleNestedAttribute{
		Description: "",
		Optional:    true,
		Attributes: map[string]rsschema.Attribute{

			"role_based": AdministratorResourcePermissionsRoleBasedSchema(),
		},
	}
}

func (o *AdministratorResourcePermissionsObject) getTypeFor(name string) attr.Type {
	schema := AdministratorResourcePermissionsSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case rsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case rsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func AdministratorResourcePermissionsRoleBasedSchema() rsschema.SingleNestedAttribute {
	return rsschema.SingleNestedAttribute{
		Description: "",
		Optional:    true,
		Attributes: map[string]rsschema.Attribute{

			"superuser": rsschema.BoolAttribute{
				Description: "Full system access",
				Optional:    true,
			},

			"superreader": rsschema.BoolAttribute{
				Description: "Read-only access to entire system",
				Optional:    true,
			},

			"deviceadmin": rsschema.BoolAttribute{
				Description: "Device administrator access (all vsys)",
				Optional:    true,
			},

			"devicereader": rsschema.BoolAttribute{
				Description: "Device read-only access (all vsys)",
				Optional:    true,
			},

			"vsysadmin": rsschema.BoolAttribute{
				Description: "Virtual system administrator access",
				Optional:    true,
			},

			"vsysreader": rsschema.BoolAttribute{
				Description: "Virtual system read-only access",
				Optional:    true,
			},

			"custom": AdministratorResourcePermissionsRoleBasedCustomSchema(),
		},
	}
}

func (o *AdministratorResourcePermissionsRoleBasedObject) getTypeFor(name string) attr.Type {
	schema := AdministratorResourcePermissionsRoleBasedSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case rsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case rsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func AdministratorResourcePermissionsRoleBasedCustomSchema() rsschema.SingleNestedAttribute {
	return rsschema.SingleNestedAttribute{
		Description: "",
		Optional:    true,
		Attributes: map[string]rsschema.Attribute{

			"profile": rsschema.StringAttribute{
				Description: "Custom admin role profile name",
				Optional:    true,
			},
		},
	}
}

func (o *AdministratorResourcePermissionsRoleBasedCustomObject) getTypeFor(name string) attr.Type {
	schema := AdministratorResourcePermissionsRoleBasedCustomSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case rsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case rsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func (o *AdministratorResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_administrator"
}

func (o *AdministratorResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = AdministratorResourceSchema()
}

// </ResourceSchema>

func (o *AdministratorResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	providerData := req.ProviderData.(*ProviderData)
	o.client = providerData.Client
	specifier, _, err := administrator.Versioning(o.client.Versioning())
	if err != nil {
		resp.Diagnostics.AddError("Failed to configure SDK client", err.Error())
		return
	}
	batchSize := providerData.MultiConfigBatchSize
	o.manager = sdkmanager.NewEntryObjectManager[*administrator.Entry, administrator.Location, *administrator.Service](o.client, administrator.NewService(o.client), batchSize, specifier, administrator.SpecMatches)
}

func (o *AdministratorResourceModel) AttributeTypes() map[string]attr.Type {

	var locationObj AdministratorLocation

	var permissionsObj *AdministratorResourcePermissionsObject
	return map[string]attr.Type{
		"location": types.ObjectType{
			AttrTypes: locationObj.AttributeTypes(),
		},
		"name":                   types.StringType,
		"authentication_profile": types.StringType,
		"public_key":             types.StringType,
		"password":               types.StringType,
		"permissions": types.ObjectType{
			AttrTypes: permissionsObj.AttributeTypes(),
		},
	}
}

func (o AdministratorResourceModel) AncestorName() string {
	return ""
}

func (o AdministratorResourceModel) EntryName() *string {
	return nil
}
func (o *AdministratorResourcePermissionsObject) AttributeTypes() map[string]attr.Type {

	var roleBasedObj *AdministratorResourcePermissionsRoleBasedObject
	return map[string]attr.Type{
		"role_based": types.ObjectType{
			AttrTypes: roleBasedObj.AttributeTypes(),
		},
	}
}

func (o AdministratorResourcePermissionsObject) AncestorName() string {
	return "permissions"
}

func (o AdministratorResourcePermissionsObject) EntryName() *string {
	return nil
}
func (o *AdministratorResourcePermissionsRoleBasedObject) AttributeTypes() map[string]attr.Type {

	var customObj *AdministratorResourcePermissionsRoleBasedCustomObject
	return map[string]attr.Type{
		"superuser":    types.BoolType,
		"superreader":  types.BoolType,
		"deviceadmin":  types.BoolType,
		"devicereader": types.BoolType,
		"vsysadmin":    types.BoolType,
		"vsysreader":   types.BoolType,
		"custom": types.ObjectType{
			AttrTypes: customObj.AttributeTypes(),
		},
	}
}

func (o AdministratorResourcePermissionsRoleBasedObject) AncestorName() string {
	return "role-based"
}

func (o AdministratorResourcePermissionsRoleBasedObject) EntryName() *string {
	return nil
}
func (o *AdministratorResourcePermissionsRoleBasedCustomObject) AttributeTypes() map[string]attr.Type {

	return map[string]attr.Type{
		"profile": types.StringType,
	}
}

func (o AdministratorResourcePermissionsRoleBasedCustomObject) AncestorName() string {
	return "custom"
}

func (o AdministratorResourcePermissionsRoleBasedCustomObject) EntryName() *string {
	return nil
}

func (o *AdministratorResourceModel) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **administrator.Entry, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	authenticationProfile_value := o.AuthenticationProfile.ValueStringPointer()
	publicKey_value := o.PublicKey.ValueStringPointer()

	var password_value *string
	{
		valueKey, err := CreateXpathForAttributeWithAncestors(ancestors, "password")
		if err != nil {
			diags.AddError("Failed to create encrypted values state key", err.Error())
			return diags
		}
		err = ev.StorePlaintextValue(valueKey, "solo", o.Password.ValueString())
		if err != nil {
			diags.AddError("Failed to manage encrypted values state", err.Error())
			return diags
		}
		password_value = o.Password.ValueStringPointer()
	}
	var permissions_entry *administrator.Permissions
	if !o.Permissions.IsUnknown() && !o.Permissions.IsNull() {
		if *obj != nil && (*obj).Permissions != nil {
			permissions_entry = (*obj).Permissions
		} else {
			permissions_entry = new(administrator.Permissions)
		}
		var object *AdministratorResourcePermissionsObject
		diags.Append(o.Permissions.As(ctx, &object, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
		diags.Append(object.CopyToPango(ctx, client, ancestors, &permissions_entry, ev)...)
		if diags.HasError() {
			return diags
		}
	}

	if (*obj) == nil {
		*obj = new(administrator.Entry)
	}
	(*obj).Name = o.Name.ValueString()
	(*obj).AuthenticationProfile = authenticationProfile_value
	(*obj).PublicKey = publicKey_value
	(*obj).Phash = password_value
	(*obj).Permissions = permissions_entry

	return diags
}
func (o *AdministratorResourcePermissionsObject) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **administrator.Permissions, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	var roleBased_entry *administrator.PermissionsRoleBased
	if !o.RoleBased.IsUnknown() && !o.RoleBased.IsNull() {
		if *obj != nil && (*obj).RoleBased != nil {
			roleBased_entry = (*obj).RoleBased
		} else {
			roleBased_entry = new(administrator.PermissionsRoleBased)
		}
		var object *AdministratorResourcePermissionsRoleBasedObject
		diags.Append(o.RoleBased.As(ctx, &object, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
		diags.Append(object.CopyToPango(ctx, client, append(ancestors, o), &roleBased_entry, ev)...)
		if diags.HasError() {
			return diags
		}
	}

	if (*obj) == nil {
		*obj = new(administrator.Permissions)
	}
	(*obj).RoleBased = roleBased_entry

	return diags
}
func (o *AdministratorResourcePermissionsRoleBasedObject) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **administrator.PermissionsRoleBased, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	superuser_value := o.Superuser.ValueBoolPointer()
	superreader_value := o.Superreader.ValueBoolPointer()
	deviceadmin_value := o.Deviceadmin.ValueBoolPointer()
	devicereader_value := o.Devicereader.ValueBoolPointer()
	vsysadmin_value := o.Vsysadmin.ValueBoolPointer()
	vsysreader_value := o.Vsysreader.ValueBoolPointer()
	var custom_entry *administrator.PermissionsRoleBasedCustom
	if !o.Custom.IsUnknown() && !o.Custom.IsNull() {
		if *obj != nil && (*obj).Custom != nil {
			custom_entry = (*obj).Custom
		} else {
			custom_entry = new(administrator.PermissionsRoleBasedCustom)
		}
		var object *AdministratorResourcePermissionsRoleBasedCustomObject
		diags.Append(o.Custom.As(ctx, &object, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
		diags.Append(object.CopyToPango(ctx, client, append(ancestors, o), &custom_entry, ev)...)
		if diags.HasError() {
			return diags
		}
	}

	if (*obj) == nil {
		*obj = new(administrator.PermissionsRoleBased)
	}
	(*obj).Superuser = superuser_value
	(*obj).Superreader = superreader_value
	(*obj).Deviceadmin = deviceadmin_value
	(*obj).Devicereader = devicereader_value
	(*obj).Vsysadmin = vsysadmin_value
	(*obj).Vsysreader = vsysreader_value
	(*obj).Custom = custom_entry

	return diags
}
func (o *AdministratorResourcePermissionsRoleBasedCustomObject) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **administrator.PermissionsRoleBasedCustom, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	profile_value := o.Profile.ValueStringPointer()

	if (*obj) == nil {
		*obj = new(administrator.PermissionsRoleBasedCustom)
	}
	(*obj).Profile = profile_value

	return diags
}

func (o *AdministratorResourceModel) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *administrator.Entry, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics

	var permissions_obj *AdministratorResourcePermissionsObject
	if o.Permissions.IsNull() {
		permissions_obj = new(AdministratorResourcePermissionsObject)
	} else {
		diags.Append(o.Permissions.As(ctx, &permissions_obj, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
	}
	permissions_object := types.ObjectNull(permissions_obj.AttributeTypes())
	if obj.Permissions != nil {
		diags.Append(permissions_obj.CopyFromPango(ctx, client, ancestors, obj.Permissions, ev)...)
		if diags.HasError() {
			return diags
		}
		var diags_tmp diag.Diagnostics
		permissions_object, diags_tmp = types.ObjectValueFrom(ctx, permissions_obj.AttributeTypes(), permissions_obj)
		diags.Append(diags_tmp...)
		if diags.HasError() {
			return diags
		}
	}

	var authenticationProfile_value types.String
	if obj.AuthenticationProfile != nil {
		authenticationProfile_value = types.StringValue(*obj.AuthenticationProfile)
	}
	var publicKey_value types.String
	if obj.PublicKey != nil {
		publicKey_value = types.StringValue(*obj.PublicKey)
	}
	var password_value types.String
	if obj.Phash != nil {
		valueKey, err := CreateXpathForAttributeWithAncestors(ancestors, "password")
		if err != nil {
			diags.AddError("Failed to create encrypted values state key", err.Error())
			return diags
		}

		if evFromState, found := ev.GetEncryptedValue(valueKey); found && ev.PreferServerState() && *obj.Phash != evFromState {
			password_value = types.StringPointerValue(obj.Phash)
		} else if value, found := ev.GetPlaintextValue(valueKey); found {
			password_value = types.StringValue(value)
		} else {
			diags.AddWarning("Failed to read plaintext value from encrypted state, fallback value used", fmt.Sprintf("Missing plaintext value for %s", valueKey))
			password_value = types.StringValue("[PLAINTEXT-VALUE-MISSING]")
		}

		if !ev.PreferServerState() {
			err = ev.StoreEncryptedValue(valueKey, "solo", *obj.Phash)
			if err != nil {
				diags.AddError("Failed to store encrypted values state", err.Error())
				return diags
			}
		}
	}
	o.Name = types.StringValue(obj.Name)
	o.AuthenticationProfile = authenticationProfile_value
	o.PublicKey = publicKey_value
	o.Password = password_value
	o.Permissions = permissions_object

	return diags
}

func (o *AdministratorResourcePermissionsObject) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *administrator.Permissions, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics

	var roleBased_obj *AdministratorResourcePermissionsRoleBasedObject
	if o.RoleBased.IsNull() {
		roleBased_obj = new(AdministratorResourcePermissionsRoleBasedObject)
	} else {
		diags.Append(o.RoleBased.As(ctx, &roleBased_obj, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
	}
	roleBased_object := types.ObjectNull(roleBased_obj.AttributeTypes())
	if obj.RoleBased != nil {
		diags.Append(roleBased_obj.CopyFromPango(ctx, client, append(ancestors, o), obj.RoleBased, ev)...)
		if diags.HasError() {
			return diags
		}
		var diags_tmp diag.Diagnostics
		roleBased_object, diags_tmp = types.ObjectValueFrom(ctx, roleBased_obj.AttributeTypes(), roleBased_obj)
		diags.Append(diags_tmp...)
		if diags.HasError() {
			return diags
		}
	}

	o.RoleBased = roleBased_object

	return diags
}

func (o *AdministratorResourcePermissionsRoleBasedObject) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *administrator.PermissionsRoleBased, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics

	var custom_obj *AdministratorResourcePermissionsRoleBasedCustomObject
	if o.Custom.IsNull() {
		custom_obj = new(AdministratorResourcePermissionsRoleBasedCustomObject)
	} else {
		diags.Append(o.Custom.As(ctx, &custom_obj, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
	}
	custom_object := types.ObjectNull(custom_obj.AttributeTypes())
	if obj.Custom != nil {
		diags.Append(custom_obj.CopyFromPango(ctx, client, append(ancestors, o), obj.Custom, ev)...)
		if diags.HasError() {
			return diags
		}
		var diags_tmp diag.Diagnostics
		custom_object, diags_tmp = types.ObjectValueFrom(ctx, custom_obj.AttributeTypes(), custom_obj)
		diags.Append(diags_tmp...)
		if diags.HasError() {
			return diags
		}
	}

	var superuser_value types.Bool
	if obj.Superuser != nil {
		superuser_value = types.BoolValue(*obj.Superuser)
	}
	var superreader_value types.Bool
	if obj.Superreader != nil {
		superreader_value = types.BoolValue(*obj.Superreader)
	}
	var deviceadmin_value types.Bool
	if obj.Deviceadmin != nil {
		deviceadmin_value = types.BoolValue(*obj.Deviceadmin)
	}
	var devicereader_value types.Bool
	if obj.Devicereader != nil {
		devicereader_value = types.BoolValue(*obj.Devicereader)
	}
	var vsysadmin_value types.Bool
	if obj.Vsysadmin != nil {
		vsysadmin_value = types.BoolValue(*obj.Vsysadmin)
	}
	var vsysreader_value types.Bool
	if obj.Vsysreader != nil {
		vsysreader_value = types.BoolValue(*obj.Vsysreader)
	}
	o.Superuser = superuser_value
	o.Superreader = superreader_value
	o.Deviceadmin = deviceadmin_value
	o.Devicereader = devicereader_value
	o.Vsysadmin = vsysadmin_value
	o.Vsysreader = vsysreader_value
	o.Custom = custom_object

	return diags
}

func (o *AdministratorResourcePermissionsRoleBasedCustomObject) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *administrator.PermissionsRoleBasedCustom, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics

	var profile_value types.String
	if obj.Profile != nil {
		profile_value = types.StringValue(*obj.Profile)
	}
	o.Profile = profile_value

	return diags
}

func (o *AdministratorResourceModel) resourceXpathParentComponents() ([]string, error) {
	var components []string
	return components, nil
}

func (o *AdministratorResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var state AdministratorResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource create", map[string]any{
		"resource_name": "panos_administrator_resource",
		"function":      "Create",
		"name":          state.Name.ValueString(),
	})

	// Verify mode.
	if o.client.Hostname == "" {
		resp.Diagnostics.AddError("Invalid mode error", InspectionModeError)
		return
	}

	var encryptedValues []byte
	ev, err := NewEncryptedValuesManager(encryptedValues, false)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read encrypted values from private state", err.Error())
		return
	}

	// Determine the location.

	var location administrator.Location

	{
		var terraformLocation AdministratorLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Panorama.IsNull() {
			location.Panorama = &administrator.PanoramaLocation{}
			var innerLocation AdministratorPanoramaLocation
			resp.Diagnostics.Append(terraformLocation.Panorama.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.Template.IsNull() {
			location.Template = &administrator.TemplateLocation{}
			var innerLocation AdministratorTemplateLocation
			resp.Diagnostics.Append(terraformLocation.Template.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Template.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.Template.Template = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateStack.IsNull() {
			location.TemplateStack = &administrator.TemplateStackLocation{}
			var innerLocation AdministratorTemplateStackLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStack.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStack.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStack.TemplateStack = innerLocation.Name.ValueString()
		}
	}

	if err := location.IsValid(); err != nil {
		resp.Diagnostics.AddError("Invalid location", err.Error())
		return
	}

	// Load the desired config.
	var obj *administrator.Entry
	resp.Diagnostics.Append(state.CopyToPango(ctx, o.client, nil, &obj, ev)...)
	if resp.Diagnostics.HasError() {
		return
	}

	/*
		// Timeout handling.
		ctx, cancel := context.WithTimeout(ctx, GetTimeout(state.Timeouts.Create))
		defer cancel()
	*/

	// Perform the operation.

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}
	created, err := o.manager.Create(ctx, location, components, obj)
	if err != nil {
		resp.Diagnostics.AddError("Error in create", err.Error())
		return
	}

	resp.Diagnostics.Append(state.CopyFromPango(ctx, o.client, nil, created, ev)...)
	if resp.Diagnostics.HasError() {
		return
	}

	payload, err := json.Marshal(ev)
	if err != nil {
		resp.Diagnostics.AddError("Failed to marshal encrypted values state", err.Error())
		return
	}
	resp.Private.SetKey(ctx, "encrypted_values", payload)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (o *AdministratorResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {

	var state AdministratorResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	encryptedValues, diags := req.Private.GetKey(ctx, "encrypted_values")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	ev, err := NewEncryptedValuesManager(encryptedValues, true)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read encrypted values from private state", err.Error())
		return
	}

	var location administrator.Location

	{
		var terraformLocation AdministratorLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Panorama.IsNull() {
			location.Panorama = &administrator.PanoramaLocation{}
			var innerLocation AdministratorPanoramaLocation
			resp.Diagnostics.Append(terraformLocation.Panorama.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.Template.IsNull() {
			location.Template = &administrator.TemplateLocation{}
			var innerLocation AdministratorTemplateLocation
			resp.Diagnostics.Append(terraformLocation.Template.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Template.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.Template.Template = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateStack.IsNull() {
			location.TemplateStack = &administrator.TemplateStackLocation{}
			var innerLocation AdministratorTemplateStackLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStack.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStack.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStack.TemplateStack = innerLocation.Name.ValueString()
		}
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource read", map[string]any{
		"resource_name": "panos_administrator_resource",
		"function":      "Read",
		"name":          state.Name.ValueString(),
	})

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}
	object, err := o.manager.Read(ctx, location, components, state.Name.ValueString())
	if err != nil {
		if errors.Is(err, sdkmanager.ErrObjectNotFound) {
			resp.State.RemoveResource(ctx)
		} else {
			resp.Diagnostics.AddError("Error reading entry", err.Error())
		}
		return
	}

	copy_diags := state.CopyFromPango(ctx, o.client, nil, object, ev)
	resp.Diagnostics.Append(copy_diags...)

	/*
			// Keep the timeouts.
		    // TODO: This won't work for state import.
			state.Timeouts = state.Timeouts
	*/

	state.Location = state.Location

	payload, err := json.Marshal(ev)
	if err != nil {
		resp.Diagnostics.AddError("Failed to marshal encrypted values state", err.Error())
		return
	}
	resp.Private.SetKey(ctx, "encrypted_values", payload)

	// Done.
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)

}
func (o *AdministratorResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {

	var plan, state AdministratorResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	encryptedValues, diags := req.Private.GetKey(ctx, "encrypted_values")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	ev, err := NewEncryptedValuesManager(encryptedValues, false)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read encrypted values from private state", err.Error())
		return
	}

	var location administrator.Location

	{
		var terraformLocation AdministratorLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Panorama.IsNull() {
			location.Panorama = &administrator.PanoramaLocation{}
			var innerLocation AdministratorPanoramaLocation
			resp.Diagnostics.Append(terraformLocation.Panorama.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.Template.IsNull() {
			location.Template = &administrator.TemplateLocation{}
			var innerLocation AdministratorTemplateLocation
			resp.Diagnostics.Append(terraformLocation.Template.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Template.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.Template.Template = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateStack.IsNull() {
			location.TemplateStack = &administrator.TemplateStackLocation{}
			var innerLocation AdministratorTemplateStackLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStack.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStack.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStack.TemplateStack = innerLocation.Name.ValueString()
		}
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource update", map[string]any{
		"resource_name": "panos_administrator_resource",
		"function":      "Update",
	})

	// Verify mode.
	if o.client.Hostname == "" {
		resp.Diagnostics.AddError("Invalid mode error", InspectionModeError)
		return
	}

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}
	var obj *administrator.Entry
	if state.Name.ValueString() != plan.Name.ValueString() {
		obj, err = o.manager.Read(ctx, location, components, state.Name.ValueString())
	} else {
		obj, err = o.manager.Read(ctx, location, components, plan.Name.ValueString())
	}
	if err != nil {
		resp.Diagnostics.AddError("Error in update", err.Error())
		return
	}

	resp.Diagnostics.Append(plan.CopyToPango(ctx, o.client, nil, &obj, ev)...)
	if resp.Diagnostics.HasError() {
		return
	}

	components, err = plan.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}

	// If name differs between plan and state, we need to set old name for the object
	// before calling SDK Update() function to properly handle rename + edit cycle.
	var newName string
	if state.Name.ValueString() != plan.Name.ValueString() {
		newName = plan.Name.ValueString()
		obj.Name = state.Name.ValueString()
	}

	updated, err := o.manager.Update(ctx, location, components, obj, newName)

	if err != nil {
		resp.Diagnostics.AddError("Error in update", err.Error())
		return
	}

	/*
		// Keep the timeouts.
		state.Timeouts = plan.Timeouts
	*/

	copy_diags := plan.CopyFromPango(ctx, o.client, nil, updated, ev)
	resp.Diagnostics.Append(copy_diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	payload, err := json.Marshal(ev)
	if err != nil {
		resp.Diagnostics.AddError("Failed to marshal encrypted values state", err.Error())
		return
	}
	resp.Private.SetKey(ctx, "encrypted_values", payload)

	// Done.
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)

}
func (o *AdministratorResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {

	var state AdministratorResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource delete", map[string]any{
		"resource_name": "panos_administrator_resource",
		"function":      "Delete",
		"name":          state.Name.ValueString(),
	})

	// Verify mode.
	if o.client.Hostname == "" {
		resp.Diagnostics.AddError("Invalid mode error", InspectionModeError)
		return
	}

	var location administrator.Location

	{
		var terraformLocation AdministratorLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Panorama.IsNull() {
			location.Panorama = &administrator.PanoramaLocation{}
			var innerLocation AdministratorPanoramaLocation
			resp.Diagnostics.Append(terraformLocation.Panorama.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.Template.IsNull() {
			location.Template = &administrator.TemplateLocation{}
			var innerLocation AdministratorTemplateLocation
			resp.Diagnostics.Append(terraformLocation.Template.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Template.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.Template.Template = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateStack.IsNull() {
			location.TemplateStack = &administrator.TemplateStackLocation{}
			var innerLocation AdministratorTemplateStackLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStack.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStack.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStack.TemplateStack = innerLocation.Name.ValueString()
		}
	}

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}

	err = o.manager.Delete(ctx, location, components, []string{state.Name.ValueString()})
	if err != nil && !errors.Is(err, sdkmanager.ErrObjectNotFound) {
		resp.Diagnostics.AddError("Error in delete", err.Error())
		return
	}

}

type AdministratorImportState struct {
	Location types.Object `json:"location"`
	Name     types.String `json:"name"`
}

func (o AdministratorImportState) MarshalJSON() ([]byte, error) {
	type shadow struct {
		Location interface{} `json:"location"`
		Name     *string     `json:"name"`
	}
	var location_object interface{}
	{
		var err error
		location_object, err = TypesObjectToMap(o.Location, AdministratorLocationSchema())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal location into JSON document: %w", err)
		}
	}

	obj := shadow{
		Location: location_object,
		Name:     o.Name.ValueStringPointer(),
	}

	return json.Marshal(obj)
}

func (o *AdministratorImportState) UnmarshalJSON(data []byte) error {
	var shadow struct {
		Location interface{} `json:"location"`
		Name     *string     `json:"name"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	var location_object types.Object
	{
		location_map, ok := shadow.Location.(map[string]interface{})
		if !ok {
			return NewDiagnosticsError("Failed to unmarshal JSON document into location: expected map[string]interface{}", nil)
		}
		var err error
		location_object, err = MapToTypesObject(location_map, AdministratorLocationSchema())
		if err != nil {
			return fmt.Errorf("failed to unmarshal location from JSON: %w", err)
		}
	}
	o.Location = location_object
	o.Name = types.StringPointerValue(shadow.Name)

	return nil
}

func AdministratorImportStateCreator(ctx context.Context, resource types.Object) ([]byte, error) {
	attrs := resource.Attributes()
	if attrs == nil {
		return nil, fmt.Errorf("Object has no attributes")
	}

	locationAttr, ok := attrs["location"]
	if !ok {
		return nil, fmt.Errorf("location attribute missing")
	}

	var location types.Object
	switch value := locationAttr.(type) {
	case types.Object:
		location = value
	default:
		return nil, fmt.Errorf("location attribute expected to be an object")
	}
	nameAttr, ok := attrs["name"]
	if !ok {
		return nil, fmt.Errorf("name attribute missing")
	}

	var name types.String
	switch value := nameAttr.(type) {
	case types.String:
		name = value
	default:
		return nil, fmt.Errorf("name attribute expected to be a string")
	}

	importStruct := AdministratorImportState{
		Location: location,
		Name:     name,
	}

	return json.Marshal(importStruct)
}

func (o *AdministratorResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {

	var obj AdministratorImportState
	data, err := base64.StdEncoding.DecodeString(req.ID)
	if err != nil {
		resp.Diagnostics.AddError("Failed to decode Import ID", err.Error())
		return
	}

	err = json.Unmarshal(data, &obj)
	if err != nil {
		var diagsErr *DiagnosticsError
		if errors.As(err, &diagsErr) {
			resp.Diagnostics.Append(diagsErr.Diagnostics()...)
		} else {
			resp.Diagnostics.AddError("Failed to unmarshal Import ID", err.Error())
		}
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("location"), obj.Location)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), obj.Name)...)
}

type AdministratorPanoramaLocation struct {
}
type AdministratorTemplateLocation struct {
	PanoramaDevice types.String `tfsdk:"panorama_device"`
	Name           types.String `tfsdk:"name"`
}
type AdministratorTemplateStackLocation struct {
	PanoramaDevice types.String `tfsdk:"panorama_device"`
	Name           types.String `tfsdk:"name"`
}
type AdministratorLocation struct {
	Panorama      types.Object `tfsdk:"panorama"`
	Template      types.Object `tfsdk:"template"`
	TemplateStack types.Object `tfsdk:"template_stack"`
}

func AdministratorLocationSchema() rsschema.Attribute {
	return rsschema.SingleNestedAttribute{
		Description: "The location of this object.",
		Required:    true,
		Attributes: map[string]rsschema.Attribute{
			"panorama": rsschema.SingleNestedAttribute{
				Description: "Panorama administrator",
				Optional:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},

				Validators: []validator.Object{
					objectvalidator.ExactlyOneOf(path.Expressions{
						path.MatchRelative().AtParent().AtName("panorama"),
						path.MatchRelative().AtParent().AtName("template"),
						path.MatchRelative().AtParent().AtName("template_stack"),
					}...),
				},
			},
			"template": rsschema.SingleNestedAttribute{
				Description: "Administrator pushed via a Panorama template",
				Optional:    true,
				Attributes: map[string]rsschema.Attribute{
					"panorama_device": rsschema.StringAttribute{
						Description: "Specific Panorama device",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("localhost.localdomain"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"name": rsschema.StringAttribute{
						Description: "Specific Panorama template",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString(""),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
				},
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
			},
			"template_stack": rsschema.SingleNestedAttribute{
				Description: "Administrator pushed via a Panorama template stack",
				Optional:    true,
				Attributes: map[string]rsschema.Attribute{
					"panorama_device": rsschema.StringAttribute{
						Description: "Specific Panorama device",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("localhost.localdomain"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"name": rsschema.StringAttribute{
						Description: "The template stack",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString(""),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
				},
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}

func (o AdministratorPanoramaLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
	}

	obj := shadow{}

	return json.Marshal(obj)
}

func (o *AdministratorPanoramaLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}

	return nil
}
func (o AdministratorTemplateLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		Name           *string `json:"name,omitempty"`
	}

	obj := shadow{
		PanoramaDevice: o.PanoramaDevice.ValueStringPointer(),
		Name:           o.Name.ValueStringPointer(),
	}

	return json.Marshal(obj)
}

func (o *AdministratorTemplateLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		Name           *string `json:"name,omitempty"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	o.PanoramaDevice = types.StringPointerValue(shadow.PanoramaDevice)
	o.Name = types.StringPointerValue(shadow.Name)

	return nil
}
func (o AdministratorTemplateStackLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		Name           *string `json:"name,omitempty"`
	}

	obj := shadow{
		PanoramaDevice: o.PanoramaDevice.ValueStringPointer(),
		Name:           o.Name.ValueStringPointer(),
	}

	return json.Marshal(obj)
}

func (o *AdministratorTemplateStackLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		Name           *string `json:"name,omitempty"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	o.PanoramaDevice = types.StringPointerValue(shadow.PanoramaDevice)
	o.Name = types.StringPointerValue(shadow.Name)

	return nil
}
func (o AdministratorLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
		Panorama      *AdministratorPanoramaLocation      `json:"panorama,omitempty"`
		Template      *AdministratorTemplateLocation      `json:"template,omitempty"`
		TemplateStack *AdministratorTemplateStackLocation `json:"template_stack,omitempty"`
	}
	var panorama_object *AdministratorPanoramaLocation
	{
		diags := o.Panorama.As(context.TODO(), &panorama_object, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			return nil, NewDiagnosticsError("Failed to marshal panorama into JSON document", diags.Errors())
		}
	}
	var template_object *AdministratorTemplateLocation
	{
		diags := o.Template.As(context.TODO(), &template_object, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			return nil, NewDiagnosticsError("Failed to marshal template into JSON document", diags.Errors())
		}
	}
	var templateStack_object *AdministratorTemplateStackLocation
	{
		diags := o.TemplateStack.As(context.TODO(), &templateStack_object, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			return nil, NewDiagnosticsError("Failed to marshal template_stack into JSON document", diags.Errors())
		}
	}

	obj := shadow{
		Panorama:      panorama_object,
		Template:      template_object,
		TemplateStack: templateStack_object,
	}

	return json.Marshal(obj)
}

func (o *AdministratorLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
		Panorama      *AdministratorPanoramaLocation      `json:"panorama,omitempty"`
		Template      *AdministratorTemplateLocation      `json:"template,omitempty"`
		TemplateStack *AdministratorTemplateStackLocation `json:"template_stack,omitempty"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	var panorama_object types.Object
	{
		var diags_tmp diag.Diagnostics
		panorama_object, diags_tmp = types.ObjectValueFrom(context.TODO(), shadow.Panorama.AttributeTypes(), shadow.Panorama)
		if diags_tmp.HasError() {
			return NewDiagnosticsError("Failed to unmarshal JSON document into panorama", diags_tmp.Errors())
		}
	}
	var template_object types.Object
	{
		var diags_tmp diag.Diagnostics
		template_object, diags_tmp = types.ObjectValueFrom(context.TODO(), shadow.Template.AttributeTypes(), shadow.Template)
		if diags_tmp.HasError() {
			return NewDiagnosticsError("Failed to unmarshal JSON document into template", diags_tmp.Errors())
		}
	}
	var templateStack_object types.Object
	{
		var diags_tmp diag.Diagnostics
		templateStack_object, diags_tmp = types.ObjectValueFrom(context.TODO(), shadow.TemplateStack.AttributeTypes(), shadow.TemplateStack)
		if diags_tmp.HasError() {
			return NewDiagnosticsError("Failed to unmarshal JSON document into template_stack", diags_tmp.Errors())
		}
	}
	o.Panorama = panorama_object
	o.Template = template_object
	o.TemplateStack = templateStack_object

	return nil
}

func (o *AdministratorPanoramaLocation) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{}
}
func (o *AdministratorTemplateLocation) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"panorama_device": types.StringType,
		"name":            types.StringType,
	}
}
func (o *AdministratorTemplateStackLocation) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"panorama_device": types.StringType,
		"name":            types.StringType,
	}
}
func (o *AdministratorLocation) AttributeTypes() map[string]attr.Type {
	var panoramaObj AdministratorPanoramaLocation
	var templateObj AdministratorTemplateLocation
	var templateStackObj AdministratorTemplateStackLocation
	return map[string]attr.Type{
		"panorama": types.ObjectType{
			AttrTypes: panoramaObj.AttributeTypes(),
		},
		"template": types.ObjectType{
			AttrTypes: templateObj.AttributeTypes(),
		},
		"template_stack": types.ObjectType{
			AttrTypes: templateStackObj.AttributeTypes(),
		},
	}
}
