package provider

// Note:  This file is automatically generated.  Manually made changes
// will be overwritten when the provider is generated.

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/PaloAltoNetworks/pango"
	"github.com/PaloAltoNetworks/pango/device/profiles/email"
	pangoutil "github.com/PaloAltoNetworks/pango/util"

	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	rsschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	sdkmanager "github.com/PaloAltoNetworks/terraform-provider-panos/internal/manager"
)

// Generate Terraform Data Source object.
var (
	_ datasource.DataSource              = &EmailServerProfileDataSource{}
	_ datasource.DataSourceWithConfigure = &EmailServerProfileDataSource{}
)

func NewEmailServerProfileDataSource() datasource.DataSource {
	return &EmailServerProfileDataSource{}
}

type EmailServerProfileDataSource struct {
	client  *pango.Client
	manager *sdkmanager.EntryObjectManager[*email.Entry, email.Location, *email.Service]
}

type EmailServerProfileDataSourceFilter struct {
	// TODO: Generate Data Source filter via function
}

type EmailServerProfileDataSourceModel struct {
	Location types.Object `tfsdk:"location"`
	Name     types.String `tfsdk:"name"`
	Servers  types.List   `tfsdk:"servers"`
	Format   types.Object `tfsdk:"format"`
}
type EmailServerProfileDataSourceServersObject struct {
	Name               types.String `tfsdk:"name"`
	From               types.String `tfsdk:"from"`
	To                 types.String `tfsdk:"to"`
	AndAlsoTo          types.String `tfsdk:"and_also_to"`
	Gateway            types.String `tfsdk:"gateway"`
	Port               types.Int64  `tfsdk:"port"`
	TlsVersion         types.String `tfsdk:"tls_version"`
	Auth               types.String `tfsdk:"auth"`
	CertificateProfile types.String `tfsdk:"certificate_profile"`
}
type EmailServerProfileDataSourceFormatObject struct {
	Auth          types.String `tfsdk:"auth"`
	Config        types.String `tfsdk:"config"`
	Correlation   types.String `tfsdk:"correlation"`
	Data          types.String `tfsdk:"data"`
	Decryption    types.String `tfsdk:"decryption"`
	Globalprotect types.String `tfsdk:"globalprotect"`
	Gtp           types.String `tfsdk:"gtp"`
	HipMatch      types.String `tfsdk:"hip_match"`
	Iptag         types.String `tfsdk:"iptag"`
	Sctp          types.String `tfsdk:"sctp"`
	System        types.String `tfsdk:"system"`
	Threat        types.String `tfsdk:"threat"`
	Traffic       types.String `tfsdk:"traffic"`
	Tunnel        types.String `tfsdk:"tunnel"`
	Url           types.String `tfsdk:"url"`
	Userid        types.String `tfsdk:"userid"`
	Wildfire      types.String `tfsdk:"wildfire"`
}

func (o *EmailServerProfileDataSourceModel) AttributeTypes() map[string]attr.Type {

	var locationObj EmailServerProfileLocation

	var serversObj *EmailServerProfileDataSourceServersObject

	var formatObj *EmailServerProfileDataSourceFormatObject
	return map[string]attr.Type{
		"location": types.ObjectType{
			AttrTypes: locationObj.AttributeTypes(),
		},
		"name": types.StringType,
		"servers": types.ListType{
			ElemType: types.ObjectType{
				AttrTypes: serversObj.AttributeTypes(),
			},
		},
		"format": types.ObjectType{
			AttrTypes: formatObj.AttributeTypes(),
		},
	}
}

func (o EmailServerProfileDataSourceModel) AncestorName() string {
	return ""
}

func (o EmailServerProfileDataSourceModel) EntryName() *string {
	return nil
}
func (o *EmailServerProfileDataSourceServersObject) AttributeTypes() map[string]attr.Type {

	return map[string]attr.Type{
		"name":                types.StringType,
		"from":                types.StringType,
		"to":                  types.StringType,
		"and_also_to":         types.StringType,
		"gateway":             types.StringType,
		"port":                types.Int64Type,
		"tls_version":         types.StringType,
		"auth":                types.StringType,
		"certificate_profile": types.StringType,
	}
}

func (o EmailServerProfileDataSourceServersObject) AncestorName() string {
	return "servers"
}

func (o EmailServerProfileDataSourceServersObject) EntryName() *string {
	return o.Name.ValueStringPointer()
}
func (o *EmailServerProfileDataSourceFormatObject) AttributeTypes() map[string]attr.Type {

	return map[string]attr.Type{
		"auth":          types.StringType,
		"config":        types.StringType,
		"correlation":   types.StringType,
		"data":          types.StringType,
		"decryption":    types.StringType,
		"globalprotect": types.StringType,
		"gtp":           types.StringType,
		"hip_match":     types.StringType,
		"iptag":         types.StringType,
		"sctp":          types.StringType,
		"system":        types.StringType,
		"threat":        types.StringType,
		"traffic":       types.StringType,
		"tunnel":        types.StringType,
		"url":           types.StringType,
		"userid":        types.StringType,
		"wildfire":      types.StringType,
	}
}

func (o EmailServerProfileDataSourceFormatObject) AncestorName() string {
	return "format"
}

func (o EmailServerProfileDataSourceFormatObject) EntryName() *string {
	return nil
}

func (o *EmailServerProfileDataSourceModel) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **email.Entry, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	var servers_tf_entries []EmailServerProfileDataSourceServersObject
	var servers_pango_entries []email.Server
	{
		d := o.Servers.ElementsAs(ctx, &servers_tf_entries, false)
		diags.Append(d...)
		if diags.HasError() {
			return diags
		}
		for _, elt := range servers_tf_entries {
			var entry *email.Server
			diags.Append(elt.CopyToPango(ctx, client, append(ancestors, elt), &entry, ev)...)
			if diags.HasError() {
				return diags
			}
			servers_pango_entries = append(servers_pango_entries, *entry)
		}
	}
	var format_entry *email.Format
	if !o.Format.IsUnknown() && !o.Format.IsNull() {
		if *obj != nil && (*obj).Format != nil {
			format_entry = (*obj).Format
		} else {
			format_entry = new(email.Format)
		}
		var object *EmailServerProfileDataSourceFormatObject
		diags.Append(o.Format.As(ctx, &object, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
		diags.Append(object.CopyToPango(ctx, client, ancestors, &format_entry, ev)...)
		if diags.HasError() {
			return diags
		}
	}

	if (*obj) == nil {
		*obj = new(email.Entry)
	}
	(*obj).Name = o.Name.ValueString()
	(*obj).Server = servers_pango_entries
	(*obj).Format = format_entry

	return diags
}
func (o *EmailServerProfileDataSourceServersObject) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **email.Server, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	from_value := o.From.ValueStringPointer()
	to_value := o.To.ValueStringPointer()
	andAlsoTo_value := o.AndAlsoTo.ValueStringPointer()
	gateway_value := o.Gateway.ValueStringPointer()
	port_value := o.Port.ValueInt64Pointer()
	tlsVersion_value := o.TlsVersion.ValueStringPointer()
	auth_value := o.Auth.ValueStringPointer()
	certificateProfile_value := o.CertificateProfile.ValueStringPointer()

	if (*obj) == nil {
		*obj = new(email.Server)
	}
	(*obj).Name = o.Name.ValueString()
	(*obj).From = from_value
	(*obj).To = to_value
	(*obj).AndAlsoTo = andAlsoTo_value
	(*obj).Gateway = gateway_value
	(*obj).Port = port_value
	(*obj).TlsVersion = tlsVersion_value
	(*obj).Auth = auth_value
	(*obj).CertificateProfile = certificateProfile_value

	return diags
}
func (o *EmailServerProfileDataSourceFormatObject) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **email.Format, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	auth_value := o.Auth.ValueStringPointer()
	config_value := o.Config.ValueStringPointer()
	correlation_value := o.Correlation.ValueStringPointer()
	data_value := o.Data.ValueStringPointer()
	decryption_value := o.Decryption.ValueStringPointer()
	globalprotect_value := o.Globalprotect.ValueStringPointer()
	gtp_value := o.Gtp.ValueStringPointer()
	hipMatch_value := o.HipMatch.ValueStringPointer()
	iptag_value := o.Iptag.ValueStringPointer()
	sctp_value := o.Sctp.ValueStringPointer()
	system_value := o.System.ValueStringPointer()
	threat_value := o.Threat.ValueStringPointer()
	traffic_value := o.Traffic.ValueStringPointer()
	tunnel_value := o.Tunnel.ValueStringPointer()
	url_value := o.Url.ValueStringPointer()
	userid_value := o.Userid.ValueStringPointer()
	wildfire_value := o.Wildfire.ValueStringPointer()

	if (*obj) == nil {
		*obj = new(email.Format)
	}
	(*obj).Auth = auth_value
	(*obj).Config = config_value
	(*obj).Correlation = correlation_value
	(*obj).Data = data_value
	(*obj).Decryption = decryption_value
	(*obj).Globalprotect = globalprotect_value
	(*obj).Gtp = gtp_value
	(*obj).HipMatch = hipMatch_value
	(*obj).Iptag = iptag_value
	(*obj).Sctp = sctp_value
	(*obj).System = system_value
	(*obj).Threat = threat_value
	(*obj).Traffic = traffic_value
	(*obj).Tunnel = tunnel_value
	(*obj).Url = url_value
	(*obj).Userid = userid_value
	(*obj).Wildfire = wildfire_value

	return diags
}

func (o *EmailServerProfileDataSourceModel) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *email.Entry, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	var servers_list types.List
	{
		var servers_tf_entries []EmailServerProfileDataSourceServersObject
		if !o.Servers.IsNull() {
			diags.Append(o.Servers.ElementsAs(ctx, &servers_tf_entries, false)...)
			if diags.HasError() {
				return diags
			}
		}

		for idx, elt := range obj.Server {
			entry := EmailServerProfileDataSourceServersObject{
				Name: types.StringValue(elt.Name),
			}
			if idx < len(servers_tf_entries) {
				entry = servers_tf_entries[idx]
			}

			diags.Append(entry.CopyFromPango(ctx, client, append(ancestors, entry), &elt, ev)...)
			if diags.HasError() {
				return diags
			}

			if idx < len(servers_tf_entries) {
				servers_tf_entries[idx] = entry
			} else {
				servers_tf_entries = append(servers_tf_entries, entry)
			}
		}
		var list_diags diag.Diagnostics
		schemaType := o.getTypeFor("servers")
		servers_list, list_diags = types.ListValueFrom(ctx, schemaType, servers_tf_entries)
		diags.Append(list_diags...)
	}

	var format_obj *EmailServerProfileDataSourceFormatObject
	if o.Format.IsNull() {
		format_obj = new(EmailServerProfileDataSourceFormatObject)
	} else {
		diags.Append(o.Format.As(ctx, &format_obj, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
	}
	format_object := types.ObjectNull(format_obj.AttributeTypes())
	if obj.Format != nil {
		diags.Append(format_obj.CopyFromPango(ctx, client, ancestors, obj.Format, ev)...)
		if diags.HasError() {
			return diags
		}
		var diags_tmp diag.Diagnostics
		format_object, diags_tmp = types.ObjectValueFrom(ctx, format_obj.AttributeTypes(), format_obj)
		diags.Append(diags_tmp...)
		if diags.HasError() {
			return diags
		}
	}

	o.Name = types.StringValue(obj.Name)
	o.Servers = servers_list
	o.Format = format_object

	return diags
}

func (o *EmailServerProfileDataSourceServersObject) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *email.Server, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics

	var from_value types.String
	if obj.From != nil {
		from_value = types.StringValue(*obj.From)
	}
	var to_value types.String
	if obj.To != nil {
		to_value = types.StringValue(*obj.To)
	}
	var andAlsoTo_value types.String
	if obj.AndAlsoTo != nil {
		andAlsoTo_value = types.StringValue(*obj.AndAlsoTo)
	}
	var gateway_value types.String
	if obj.Gateway != nil {
		gateway_value = types.StringValue(*obj.Gateway)
	}
	var port_value types.Int64
	if obj.Port != nil {
		port_value = types.Int64Value(*obj.Port)
	}
	var tlsVersion_value types.String
	if obj.TlsVersion != nil {
		tlsVersion_value = types.StringValue(*obj.TlsVersion)
	}
	var auth_value types.String
	if obj.Auth != nil {
		auth_value = types.StringValue(*obj.Auth)
	}
	var certificateProfile_value types.String
	if obj.CertificateProfile != nil {
		certificateProfile_value = types.StringValue(*obj.CertificateProfile)
	}
	o.Name = types.StringValue(obj.Name)
	o.From = from_value
	o.To = to_value
	o.AndAlsoTo = andAlsoTo_value
	o.Gateway = gateway_value
	o.Port = port_value
	o.TlsVersion = tlsVersion_value
	o.Auth = auth_value
	o.CertificateProfile = certificateProfile_value

	return diags
}

func (o *EmailServerProfileDataSourceFormatObject) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *email.Format, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics

	var auth_value types.String
	if obj.Auth != nil {
		auth_value = types.StringValue(*obj.Auth)
	}
	var config_value types.String
	if obj.Config != nil {
		config_value = types.StringValue(*obj.Config)
	}
	var correlation_value types.String
	if obj.Correlation != nil {
		correlation_value = types.StringValue(*obj.Correlation)
	}
	var data_value types.String
	if obj.Data != nil {
		data_value = types.StringValue(*obj.Data)
	}
	var decryption_value types.String
	if obj.Decryption != nil {
		decryption_value = types.StringValue(*obj.Decryption)
	}
	var globalprotect_value types.String
	if obj.Globalprotect != nil {
		globalprotect_value = types.StringValue(*obj.Globalprotect)
	}
	var gtp_value types.String
	if obj.Gtp != nil {
		gtp_value = types.StringValue(*obj.Gtp)
	}
	var hipMatch_value types.String
	if obj.HipMatch != nil {
		hipMatch_value = types.StringValue(*obj.HipMatch)
	}
	var iptag_value types.String
	if obj.Iptag != nil {
		iptag_value = types.StringValue(*obj.Iptag)
	}
	var sctp_value types.String
	if obj.Sctp != nil {
		sctp_value = types.StringValue(*obj.Sctp)
	}
	var system_value types.String
	if obj.System != nil {
		system_value = types.StringValue(*obj.System)
	}
	var threat_value types.String
	if obj.Threat != nil {
		threat_value = types.StringValue(*obj.Threat)
	}
	var traffic_value types.String
	if obj.Traffic != nil {
		traffic_value = types.StringValue(*obj.Traffic)
	}
	var tunnel_value types.String
	if obj.Tunnel != nil {
		tunnel_value = types.StringValue(*obj.Tunnel)
	}
	var url_value types.String
	if obj.Url != nil {
		url_value = types.StringValue(*obj.Url)
	}
	var userid_value types.String
	if obj.Userid != nil {
		userid_value = types.StringValue(*obj.Userid)
	}
	var wildfire_value types.String
	if obj.Wildfire != nil {
		wildfire_value = types.StringValue(*obj.Wildfire)
	}
	o.Auth = auth_value
	o.Config = config_value
	o.Correlation = correlation_value
	o.Data = data_value
	o.Decryption = decryption_value
	o.Globalprotect = globalprotect_value
	o.Gtp = gtp_value
	o.HipMatch = hipMatch_value
	o.Iptag = iptag_value
	o.Sctp = sctp_value
	o.System = system_value
	o.Threat = threat_value
	o.Traffic = traffic_value
	o.Tunnel = tunnel_value
	o.Url = url_value
	o.Userid = userid_value
	o.Wildfire = wildfire_value

	return diags
}

func (o *EmailServerProfileDataSourceModel) resourceXpathParentComponents() ([]string, error) {
	var components []string
	return components, nil
}

func EmailServerProfileDataSourceSchema() dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{

			"location": EmailServerProfileDataSourceLocationSchema(),

			"name": dsschema.StringAttribute{
				Description: "",
				Required:    true,
			},

			"servers": dsschema.ListNestedAttribute{
				Description:  "List of email servers",
				Optional:     true,
				Computed:     true,
				NestedObject: EmailServerProfileDataSourceServersSchema(),
			},

			"format": EmailServerProfileDataSourceFormatSchema(),
		},
	}
}

func (o *EmailServerProfileDataSourceModel) getTypeFor(name string) attr.Type {
	schema := EmailServerProfileDataSourceSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case dsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case dsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func EmailServerProfileDataSourceServersSchema() dsschema.NestedAttributeObject {
	return dsschema.NestedAttributeObject{
		Attributes: map[string]dsschema.Attribute{

			"name": dsschema.StringAttribute{
				Description: "",
				Required:    true,
			},

			"from": dsschema.StringAttribute{
				Description: "From email address",
				Optional:    true,
				Computed:    true,
			},

			"to": dsschema.StringAttribute{
				Description: "To email address",
				Optional:    true,
				Computed:    true,
			},

			"and_also_to": dsschema.StringAttribute{
				Description: "Additional CC email address",
				Optional:    true,
				Computed:    true,
			},

			"gateway": dsschema.StringAttribute{
				Description: "IP address or FQDN of SMTP gateway",
				Optional:    true,
				Computed:    true,
			},

			"port": dsschema.Int64Attribute{
				Description: "SMTP port number",
				Optional:    true,
				Computed:    true,
			},

			"tls_version": dsschema.StringAttribute{
				Description: "Minimum TLS version for SMTP connection",
				Optional:    true,
				Computed:    true,
			},

			"auth": dsschema.StringAttribute{
				Description: "Authentication method for SMTP",
				Optional:    true,
				Computed:    true,
			},

			"certificate_profile": dsschema.StringAttribute{
				Description: "Certificate profile for TLS verification",
				Optional:    true,
				Computed:    true,
			},
		},
	}
}

func (o *EmailServerProfileDataSourceServersObject) getTypeFor(name string) attr.Type {
	schema := EmailServerProfileDataSourceServersSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case dsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case dsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func EmailServerProfileDataSourceFormatSchema() dsschema.SingleNestedAttribute {
	return dsschema.SingleNestedAttribute{
		Description: "",
		Optional:    true,
		Computed:    true,
		Attributes: map[string]dsschema.Attribute{

			"auth": dsschema.StringAttribute{
				Description: "Custom format for auth log",
				Optional:    true,
				Computed:    true,
			},

			"config": dsschema.StringAttribute{
				Description: "Custom format for config log",
				Optional:    true,
				Computed:    true,
			},

			"correlation": dsschema.StringAttribute{
				Description: "Custom format for correlation log",
				Optional:    true,
				Computed:    true,
			},

			"data": dsschema.StringAttribute{
				Description: "Custom format for data log",
				Optional:    true,
				Computed:    true,
			},

			"decryption": dsschema.StringAttribute{
				Description: "Custom format for decryption log",
				Optional:    true,
				Computed:    true,
			},

			"globalprotect": dsschema.StringAttribute{
				Description: "Custom format for globalprotect log",
				Optional:    true,
				Computed:    true,
			},

			"gtp": dsschema.StringAttribute{
				Description: "Custom format for gtp log",
				Optional:    true,
				Computed:    true,
			},

			"hip_match": dsschema.StringAttribute{
				Description: "Custom format for hip-match log",
				Optional:    true,
				Computed:    true,
			},

			"iptag": dsschema.StringAttribute{
				Description: "Custom format for iptag log",
				Optional:    true,
				Computed:    true,
			},

			"sctp": dsschema.StringAttribute{
				Description: "Custom format for sctp log",
				Optional:    true,
				Computed:    true,
			},

			"system": dsschema.StringAttribute{
				Description: "Custom format for system log",
				Optional:    true,
				Computed:    true,
			},

			"threat": dsschema.StringAttribute{
				Description: "Custom format for threat log",
				Optional:    true,
				Computed:    true,
			},

			"traffic": dsschema.StringAttribute{
				Description: "Custom format for traffic log",
				Optional:    true,
				Computed:    true,
			},

			"tunnel": dsschema.StringAttribute{
				Description: "Custom format for tunnel log",
				Optional:    true,
				Computed:    true,
			},

			"url": dsschema.StringAttribute{
				Description: "Custom format for url log",
				Optional:    true,
				Computed:    true,
			},

			"userid": dsschema.StringAttribute{
				Description: "Custom format for userid log",
				Optional:    true,
				Computed:    true,
			},

			"wildfire": dsschema.StringAttribute{
				Description: "Custom format for wildfire log",
				Optional:    true,
				Computed:    true,
			},
		},
	}
}

func (o *EmailServerProfileDataSourceFormatObject) getTypeFor(name string) attr.Type {
	schema := EmailServerProfileDataSourceFormatSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case dsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case dsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func EmailServerProfileDataSourceLocationSchema() rsschema.Attribute {
	return EmailServerProfileLocationSchema()
}

// Metadata returns the data source type name.
func (d *EmailServerProfileDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_email_server_profile"
}

// Schema defines the schema for this data source.
func (d *EmailServerProfileDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = EmailServerProfileDataSourceSchema()
}

// Configure prepares the struct.
func (d *EmailServerProfileDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	providerData := req.ProviderData.(*ProviderData)
	d.client = providerData.Client
	specifier, _, err := email.Versioning(d.client.Versioning())
	if err != nil {
		resp.Diagnostics.AddError("Failed to configure SDK client", err.Error())
		return
	}
	batchSize := providerData.MultiConfigBatchSize
	d.manager = sdkmanager.NewEntryObjectManager[*email.Entry, email.Location, *email.Service](d.client, email.NewService(d.client), batchSize, specifier, email.SpecMatches)
}
func (o *EmailServerProfileDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {

	var state EmailServerProfileDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var encryptedValues []byte
	ev, err := NewEncryptedValuesManager(encryptedValues, true)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read encrypted values from private state", err.Error())
		return
	}

	var location email.Location

	{
		var terraformLocation EmailServerProfileLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Panorama.IsNull() {
			location.Panorama = &email.PanoramaLocation{}
			var innerLocation EmailServerProfilePanoramaLocation
			resp.Diagnostics.Append(terraformLocation.Panorama.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.Vsys.IsNull() {
			location.Vsys = &email.VsysLocation{}
			var innerLocation EmailServerProfileVsysLocation
			resp.Diagnostics.Append(terraformLocation.Vsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Vsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.Vsys.Vsys = innerLocation.Name.ValueString()
		}

		if !terraformLocation.Template.IsNull() {
			location.Template = &email.TemplateLocation{}
			var innerLocation EmailServerProfileTemplateLocation
			resp.Diagnostics.Append(terraformLocation.Template.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Template.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.Template.Template = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateVsys.IsNull() {
			location.TemplateVsys = &email.TemplateVsysLocation{}
			var innerLocation EmailServerProfileTemplateVsysLocation
			resp.Diagnostics.Append(terraformLocation.TemplateVsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateVsys.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateVsys.Template = innerLocation.Template.ValueString()
			location.TemplateVsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.TemplateVsys.Vsys = innerLocation.Vsys.ValueString()
		}

		if !terraformLocation.TemplateStack.IsNull() {
			location.TemplateStack = &email.TemplateStackLocation{}
			var innerLocation EmailServerProfileTemplateStackLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStack.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStack.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStack.TemplateStack = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateStackVsys.IsNull() {
			location.TemplateStackVsys = &email.TemplateStackVsysLocation{}
			var innerLocation EmailServerProfileTemplateStackVsysLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStackVsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStackVsys.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStackVsys.TemplateStack = innerLocation.TemplateStack.ValueString()
			location.TemplateStackVsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.TemplateStackVsys.Vsys = innerLocation.Vsys.ValueString()
		}
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource read", map[string]any{
		"resource_name": "panos_email_server_profile_resource",
		"function":      "Read",
		"name":          state.Name.ValueString(),
	})

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}
	object, err := o.manager.Read(ctx, location, components, state.Name.ValueString())
	if err != nil {
		if errors.Is(err, sdkmanager.ErrObjectNotFound) {
			resp.Diagnostics.AddError("Error reading data", err.Error())
		} else {
			resp.Diagnostics.AddError("Error reading entry", err.Error())
		}
		return
	}

	copy_diags := state.CopyFromPango(ctx, o.client, nil, object, ev)
	resp.Diagnostics.Append(copy_diags...)

	/*
			// Keep the timeouts.
		    // TODO: This won't work for state import.
			state.Timeouts = state.Timeouts
	*/

	state.Location = state.Location

	// Done.
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)

}

// Generate Terraform Resource object
var (
	_ resource.Resource                = &EmailServerProfileResource{}
	_ resource.ResourceWithConfigure   = &EmailServerProfileResource{}
	_ resource.ResourceWithImportState = &EmailServerProfileResource{}
)

func NewEmailServerProfileResource() resource.Resource {
	if _, found := resourceFuncMap["panos_email_server_profile"]; !found {
		resourceFuncMap["panos_email_server_profile"] = resourceFuncs{
			CreateImportId: EmailServerProfileImportStateCreator,
		}
	}
	return &EmailServerProfileResource{}
}

type EmailServerProfileResource struct {
	client  *pango.Client
	manager *sdkmanager.EntryObjectManager[*email.Entry, email.Location, *email.Service]
}

func EmailServerProfileResourceLocationSchema() rsschema.Attribute {
	return EmailServerProfileLocationSchema()
}

type EmailServerProfileResourceModel struct {
	Location types.Object `tfsdk:"location"`
	Name     types.String `tfsdk:"name"`
	Servers  types.List   `tfsdk:"servers"`
	Format   types.Object `tfsdk:"format"`
}
type EmailServerProfileResourceServersObject struct {
	Name               types.String `tfsdk:"name"`
	From               types.String `tfsdk:"from"`
	To                 types.String `tfsdk:"to"`
	AndAlsoTo          types.String `tfsdk:"and_also_to"`
	Gateway            types.String `tfsdk:"gateway"`
	Port               types.Int64  `tfsdk:"port"`
	TlsVersion         types.String `tfsdk:"tls_version"`
	Auth               types.String `tfsdk:"auth"`
	CertificateProfile types.String `tfsdk:"certificate_profile"`
}
type EmailServerProfileResourceFormatObject struct {
	Auth          types.String `tfsdk:"auth"`
	Config        types.String `tfsdk:"config"`
	Correlation   types.String `tfsdk:"correlation"`
	Data          types.String `tfsdk:"data"`
	Decryption    types.String `tfsdk:"decryption"`
	Globalprotect types.String `tfsdk:"globalprotect"`
	Gtp           types.String `tfsdk:"gtp"`
	HipMatch      types.String `tfsdk:"hip_match"`
	Iptag         types.String `tfsdk:"iptag"`
	Sctp          types.String `tfsdk:"sctp"`
	System        types.String `tfsdk:"system"`
	Threat        types.String `tfsdk:"threat"`
	Traffic       types.String `tfsdk:"traffic"`
	Tunnel        types.String `tfsdk:"tunnel"`
	Url           types.String `tfsdk:"url"`
	Userid        types.String `tfsdk:"userid"`
	Wildfire      types.String `tfsdk:"wildfire"`
}

func (o *EmailServerProfileResourceModel) ValidateConfig(ctx context.Context, resp *resource.ValidateConfigResponse, path path.Path) {
	if !o.Servers.IsUnknown() && !o.Servers.IsNull() {
		var elements []EmailServerProfileResourceServersObject
		diags := o.Servers.ElementsAs(ctx, &elements, false)
		if diags.HasError() {
			resp.Diagnostics.Append(diags...)
		} else {
			for i, element := range elements {
				element.ValidateConfig(ctx, resp, path.AtName("servers").AtListIndex(i))
			}
		}
	}
	if !o.Format.IsUnknown() && !o.Format.IsNull() {
		var nestedObj EmailServerProfileResourceFormatObject
		diags := o.Format.As(ctx, &nestedObj, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			resp.Diagnostics.Append(diags...)
		} else {
			nestedObj.ValidateConfig(ctx, resp, path.AtName("format"))
		}
	}
}

func (o *EmailServerProfileResourceServersObject) ValidateConfig(ctx context.Context, resp *resource.ValidateConfigResponse, path path.Path) {
}

func (o *EmailServerProfileResourceFormatObject) ValidateConfig(ctx context.Context, resp *resource.ValidateConfigResponse, path path.Path) {
}

func (o *EmailServerProfileResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {

	var resource EmailServerProfileResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &resource)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resource.ValidateConfig(ctx, resp, path.Empty())
}

// <ResourceSchema>

func EmailServerProfileResourceSchema() rsschema.Schema {
	return rsschema.Schema{
		Attributes: map[string]rsschema.Attribute{

			"location": EmailServerProfileResourceLocationSchema(),

			"name": rsschema.StringAttribute{
				Description: "",
				Required:    true,
			},

			"servers": rsschema.ListNestedAttribute{
				Description:  "List of email servers",
				Optional:     true,
				NestedObject: EmailServerProfileResourceServersSchema(),
			},

			"format": EmailServerProfileResourceFormatSchema(),
		},
	}
}

func (o *EmailServerProfileResourceModel) getTypeFor(name string) attr.Type {
	schema := EmailServerProfileResourceSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case rsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case rsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func EmailServerProfileResourceServersSchema() rsschema.NestedAttributeObject {
	return rsschema.NestedAttributeObject{
		Attributes: map[string]rsschema.Attribute{

			"name": rsschema.StringAttribute{
				Description: "",
				Required:    true,
			},

			"from": rsschema.StringAttribute{
				Description: "From email address",
				Optional:    true,
			},

			"to": rsschema.StringAttribute{
				Description: "To email address",
				Optional:    true,
			},

			"and_also_to": rsschema.StringAttribute{
				Description: "Additional CC email address",
				Optional:    true,
			},

			"gateway": rsschema.StringAttribute{
				Description: "IP address or FQDN of SMTP gateway",
				Optional:    true,
			},

			"port": rsschema.Int64Attribute{
				Description: "SMTP port number",
				Optional:    true,
				Computed:    true,
				Default:     int64default.StaticInt64(25),
			},

			"tls_version": rsschema.StringAttribute{
				Description: "Minimum TLS version for SMTP connection",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("1.2"),
			},

			"auth": rsschema.StringAttribute{
				Description: "Authentication method for SMTP",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("Auto"),
			},

			"certificate_profile": rsschema.StringAttribute{
				Description: "Certificate profile for TLS verification",
				Optional:    true,
			},
		},
	}
}

func (o *EmailServerProfileResourceServersObject) getTypeFor(name string) attr.Type {
	schema := EmailServerProfileResourceServersSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case rsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case rsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func EmailServerProfileResourceFormatSchema() rsschema.SingleNestedAttribute {
	return rsschema.SingleNestedAttribute{
		Description: "",
		Optional:    true,
		Attributes: map[string]rsschema.Attribute{

			"auth": rsschema.StringAttribute{
				Description: "Custom format for auth log",
				Optional:    true,
			},

			"config": rsschema.StringAttribute{
				Description: "Custom format for config log",
				Optional:    true,
			},

			"correlation": rsschema.StringAttribute{
				Description: "Custom format for correlation log",
				Optional:    true,
			},

			"data": rsschema.StringAttribute{
				Description: "Custom format for data log",
				Optional:    true,
			},

			"decryption": rsschema.StringAttribute{
				Description: "Custom format for decryption log",
				Optional:    true,
			},

			"globalprotect": rsschema.StringAttribute{
				Description: "Custom format for globalprotect log",
				Optional:    true,
			},

			"gtp": rsschema.StringAttribute{
				Description: "Custom format for gtp log",
				Optional:    true,
			},

			"hip_match": rsschema.StringAttribute{
				Description: "Custom format for hip-match log",
				Optional:    true,
			},

			"iptag": rsschema.StringAttribute{
				Description: "Custom format for iptag log",
				Optional:    true,
			},

			"sctp": rsschema.StringAttribute{
				Description: "Custom format for sctp log",
				Optional:    true,
			},

			"system": rsschema.StringAttribute{
				Description: "Custom format for system log",
				Optional:    true,
			},

			"threat": rsschema.StringAttribute{
				Description: "Custom format for threat log",
				Optional:    true,
			},

			"traffic": rsschema.StringAttribute{
				Description: "Custom format for traffic log",
				Optional:    true,
			},

			"tunnel": rsschema.StringAttribute{
				Description: "Custom format for tunnel log",
				Optional:    true,
			},

			"url": rsschema.StringAttribute{
				Description: "Custom format for url log",
				Optional:    true,
			},

			"userid": rsschema.StringAttribute{
				Description: "Custom format for userid log",
				Optional:    true,
			},

			"wildfire": rsschema.StringAttribute{
				Description: "Custom format for wildfire log",
				Optional:    true,
			},
		},
	}
}

func (o *EmailServerProfileResourceFormatObject) getTypeFor(name string) attr.Type {
	schema := EmailServerProfileResourceFormatSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case rsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case rsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func (o *EmailServerProfileResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_email_server_profile"
}

func (o *EmailServerProfileResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = EmailServerProfileResourceSchema()
}

// </ResourceSchema>

func (o *EmailServerProfileResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	providerData := req.ProviderData.(*ProviderData)
	o.client = providerData.Client
	specifier, _, err := email.Versioning(o.client.Versioning())
	if err != nil {
		resp.Diagnostics.AddError("Failed to configure SDK client", err.Error())
		return
	}
	batchSize := providerData.MultiConfigBatchSize
	o.manager = sdkmanager.NewEntryObjectManager[*email.Entry, email.Location, *email.Service](o.client, email.NewService(o.client), batchSize, specifier, email.SpecMatches)
}

func (o *EmailServerProfileResourceModel) AttributeTypes() map[string]attr.Type {

	var locationObj EmailServerProfileLocation

	var serversObj *EmailServerProfileResourceServersObject

	var formatObj *EmailServerProfileResourceFormatObject
	return map[string]attr.Type{
		"location": types.ObjectType{
			AttrTypes: locationObj.AttributeTypes(),
		},
		"name": types.StringType,
		"servers": types.ListType{
			ElemType: types.ObjectType{
				AttrTypes: serversObj.AttributeTypes(),
			},
		},
		"format": types.ObjectType{
			AttrTypes: formatObj.AttributeTypes(),
		},
	}
}

func (o EmailServerProfileResourceModel) AncestorName() string {
	return ""
}

func (o EmailServerProfileResourceModel) EntryName() *string {
	return nil
}
func (o *EmailServerProfileResourceServersObject) AttributeTypes() map[string]attr.Type {

	return map[string]attr.Type{
		"name":                types.StringType,
		"from":                types.StringType,
		"to":                  types.StringType,
		"and_also_to":         types.StringType,
		"gateway":             types.StringType,
		"port":                types.Int64Type,
		"tls_version":         types.StringType,
		"auth":                types.StringType,
		"certificate_profile": types.StringType,
	}
}

func (o EmailServerProfileResourceServersObject) AncestorName() string {
	return "servers"
}

func (o EmailServerProfileResourceServersObject) EntryName() *string {
	return o.Name.ValueStringPointer()
}
func (o *EmailServerProfileResourceFormatObject) AttributeTypes() map[string]attr.Type {

	return map[string]attr.Type{
		"auth":          types.StringType,
		"config":        types.StringType,
		"correlation":   types.StringType,
		"data":          types.StringType,
		"decryption":    types.StringType,
		"globalprotect": types.StringType,
		"gtp":           types.StringType,
		"hip_match":     types.StringType,
		"iptag":         types.StringType,
		"sctp":          types.StringType,
		"system":        types.StringType,
		"threat":        types.StringType,
		"traffic":       types.StringType,
		"tunnel":        types.StringType,
		"url":           types.StringType,
		"userid":        types.StringType,
		"wildfire":      types.StringType,
	}
}

func (o EmailServerProfileResourceFormatObject) AncestorName() string {
	return "format"
}

func (o EmailServerProfileResourceFormatObject) EntryName() *string {
	return nil
}

func (o *EmailServerProfileResourceModel) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **email.Entry, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	var servers_tf_entries []EmailServerProfileResourceServersObject
	var servers_pango_entries []email.Server
	{
		d := o.Servers.ElementsAs(ctx, &servers_tf_entries, false)
		diags.Append(d...)
		if diags.HasError() {
			return diags
		}
		for _, elt := range servers_tf_entries {
			var entry *email.Server
			diags.Append(elt.CopyToPango(ctx, client, append(ancestors, elt), &entry, ev)...)
			if diags.HasError() {
				return diags
			}
			servers_pango_entries = append(servers_pango_entries, *entry)
		}
	}
	var format_entry *email.Format
	if !o.Format.IsUnknown() && !o.Format.IsNull() {
		if *obj != nil && (*obj).Format != nil {
			format_entry = (*obj).Format
		} else {
			format_entry = new(email.Format)
		}
		var object *EmailServerProfileResourceFormatObject
		diags.Append(o.Format.As(ctx, &object, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
		diags.Append(object.CopyToPango(ctx, client, ancestors, &format_entry, ev)...)
		if diags.HasError() {
			return diags
		}
	}

	if (*obj) == nil {
		*obj = new(email.Entry)
	}
	(*obj).Name = o.Name.ValueString()
	(*obj).Server = servers_pango_entries
	(*obj).Format = format_entry

	return diags
}
func (o *EmailServerProfileResourceServersObject) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **email.Server, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	from_value := o.From.ValueStringPointer()
	to_value := o.To.ValueStringPointer()
	andAlsoTo_value := o.AndAlsoTo.ValueStringPointer()
	gateway_value := o.Gateway.ValueStringPointer()
	port_value := o.Port.ValueInt64Pointer()
	tlsVersion_value := o.TlsVersion.ValueStringPointer()
	auth_value := o.Auth.ValueStringPointer()
	certificateProfile_value := o.CertificateProfile.ValueStringPointer()

	if (*obj) == nil {
		*obj = new(email.Server)
	}
	(*obj).Name = o.Name.ValueString()
	(*obj).From = from_value
	(*obj).To = to_value
	(*obj).AndAlsoTo = andAlsoTo_value
	(*obj).Gateway = gateway_value
	(*obj).Port = port_value
	(*obj).TlsVersion = tlsVersion_value
	(*obj).Auth = auth_value
	(*obj).CertificateProfile = certificateProfile_value

	return diags
}
func (o *EmailServerProfileResourceFormatObject) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **email.Format, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	auth_value := o.Auth.ValueStringPointer()
	config_value := o.Config.ValueStringPointer()
	correlation_value := o.Correlation.ValueStringPointer()
	data_value := o.Data.ValueStringPointer()
	decryption_value := o.Decryption.ValueStringPointer()
	globalprotect_value := o.Globalprotect.ValueStringPointer()
	gtp_value := o.Gtp.ValueStringPointer()
	hipMatch_value := o.HipMatch.ValueStringPointer()
	iptag_value := o.Iptag.ValueStringPointer()
	sctp_value := o.Sctp.ValueStringPointer()
	system_value := o.System.ValueStringPointer()
	threat_value := o.Threat.ValueStringPointer()
	traffic_value := o.Traffic.ValueStringPointer()
	tunnel_value := o.Tunnel.ValueStringPointer()
	url_value := o.Url.ValueStringPointer()
	userid_value := o.Userid.ValueStringPointer()
	wildfire_value := o.Wildfire.ValueStringPointer()

	if (*obj) == nil {
		*obj = new(email.Format)
	}
	(*obj).Auth = auth_value
	(*obj).Config = config_value
	(*obj).Correlation = correlation_value
	(*obj).Data = data_value
	(*obj).Decryption = decryption_value
	(*obj).Globalprotect = globalprotect_value
	(*obj).Gtp = gtp_value
	(*obj).HipMatch = hipMatch_value
	(*obj).Iptag = iptag_value
	(*obj).Sctp = sctp_value
	(*obj).System = system_value
	(*obj).Threat = threat_value
	(*obj).Traffic = traffic_value
	(*obj).Tunnel = tunnel_value
	(*obj).Url = url_value
	(*obj).Userid = userid_value
	(*obj).Wildfire = wildfire_value

	return diags
}

func (o *EmailServerProfileResourceModel) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *email.Entry, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	var servers_list types.List
	{
		var servers_tf_entries []EmailServerProfileResourceServersObject
		if !o.Servers.IsNull() {
			diags.Append(o.Servers.ElementsAs(ctx, &servers_tf_entries, false)...)
			if diags.HasError() {
				return diags
			}
		}

		for idx, elt := range obj.Server {
			entry := EmailServerProfileResourceServersObject{
				Name: types.StringValue(elt.Name),
			}
			if idx < len(servers_tf_entries) {
				entry = servers_tf_entries[idx]
			}

			diags.Append(entry.CopyFromPango(ctx, client, append(ancestors, entry), &elt, ev)...)
			if diags.HasError() {
				return diags
			}

			if idx < len(servers_tf_entries) {
				servers_tf_entries[idx] = entry
			} else {
				servers_tf_entries = append(servers_tf_entries, entry)
			}
		}
		var list_diags diag.Diagnostics
		schemaType := o.getTypeFor("servers")
		servers_list, list_diags = types.ListValueFrom(ctx, schemaType, servers_tf_entries)
		diags.Append(list_diags...)
	}

	var format_obj *EmailServerProfileResourceFormatObject
	if o.Format.IsNull() {
		format_obj = new(EmailServerProfileResourceFormatObject)
	} else {
		diags.Append(o.Format.As(ctx, &format_obj, basetypes.ObjectAsOptions{})...)
		if diags.HasError() {
			return diags
		}
	}
	format_object := types.ObjectNull(format_obj.AttributeTypes())
	if obj.Format != nil {
		diags.Append(format_obj.CopyFromPango(ctx, client, ancestors, obj.Format, ev)...)
		if diags.HasError() {
			return diags
		}
		var diags_tmp diag.Diagnostics
		format_object, diags_tmp = types.ObjectValueFrom(ctx, format_obj.AttributeTypes(), format_obj)
		diags.Append(diags_tmp...)
		if diags.HasError() {
			return diags
		}
	}

	o.Name = types.StringValue(obj.Name)
	o.Servers = servers_list
	o.Format = format_object

	return diags
}

func (o *EmailServerProfileResourceServersObject) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *email.Server, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics

	var from_value types.String
	if obj.From != nil {
		from_value = types.StringValue(*obj.From)
	}
	var to_value types.String
	if obj.To != nil {
		to_value = types.StringValue(*obj.To)
	}
	var andAlsoTo_value types.String
	if obj.AndAlsoTo != nil {
		andAlsoTo_value = types.StringValue(*obj.AndAlsoTo)
	}
	var gateway_value types.String
	if obj.Gateway != nil {
		gateway_value = types.StringValue(*obj.Gateway)
	}
	var port_value types.Int64
	if obj.Port != nil {
		port_value = types.Int64Value(*obj.Port)
	}
	var tlsVersion_value types.String
	if obj.TlsVersion != nil {
		tlsVersion_value = types.StringValue(*obj.TlsVersion)
	}
	var auth_value types.String
	if obj.Auth != nil {
		auth_value = types.StringValue(*obj.Auth)
	}
	var certificateProfile_value types.String
	if obj.CertificateProfile != nil {
		certificateProfile_value = types.StringValue(*obj.CertificateProfile)
	}
	o.Name = types.StringValue(obj.Name)
	o.From = from_value
	o.To = to_value
	o.AndAlsoTo = andAlsoTo_value
	o.Gateway = gateway_value
	o.Port = port_value
	o.TlsVersion = tlsVersion_value
	o.Auth = auth_value
	o.CertificateProfile = certificateProfile_value

	return diags
}

func (o *EmailServerProfileResourceFormatObject) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *email.Format, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics

	var auth_value types.String
	if obj.Auth != nil {
		auth_value = types.StringValue(*obj.Auth)
	}
	var config_value types.String
	if obj.Config != nil {
		config_value = types.StringValue(*obj.Config)
	}
	var correlation_value types.String
	if obj.Correlation != nil {
		correlation_value = types.StringValue(*obj.Correlation)
	}
	var data_value types.String
	if obj.Data != nil {
		data_value = types.StringValue(*obj.Data)
	}
	var decryption_value types.String
	if obj.Decryption != nil {
		decryption_value = types.StringValue(*obj.Decryption)
	}
	var globalprotect_value types.String
	if obj.Globalprotect != nil {
		globalprotect_value = types.StringValue(*obj.Globalprotect)
	}
	var gtp_value types.String
	if obj.Gtp != nil {
		gtp_value = types.StringValue(*obj.Gtp)
	}
	var hipMatch_value types.String
	if obj.HipMatch != nil {
		hipMatch_value = types.StringValue(*obj.HipMatch)
	}
	var iptag_value types.String
	if obj.Iptag != nil {
		iptag_value = types.StringValue(*obj.Iptag)
	}
	var sctp_value types.String
	if obj.Sctp != nil {
		sctp_value = types.StringValue(*obj.Sctp)
	}
	var system_value types.String
	if obj.System != nil {
		system_value = types.StringValue(*obj.System)
	}
	var threat_value types.String
	if obj.Threat != nil {
		threat_value = types.StringValue(*obj.Threat)
	}
	var traffic_value types.String
	if obj.Traffic != nil {
		traffic_value = types.StringValue(*obj.Traffic)
	}
	var tunnel_value types.String
	if obj.Tunnel != nil {
		tunnel_value = types.StringValue(*obj.Tunnel)
	}
	var url_value types.String
	if obj.Url != nil {
		url_value = types.StringValue(*obj.Url)
	}
	var userid_value types.String
	if obj.Userid != nil {
		userid_value = types.StringValue(*obj.Userid)
	}
	var wildfire_value types.String
	if obj.Wildfire != nil {
		wildfire_value = types.StringValue(*obj.Wildfire)
	}
	o.Auth = auth_value
	o.Config = config_value
	o.Correlation = correlation_value
	o.Data = data_value
	o.Decryption = decryption_value
	o.Globalprotect = globalprotect_value
	o.Gtp = gtp_value
	o.HipMatch = hipMatch_value
	o.Iptag = iptag_value
	o.Sctp = sctp_value
	o.System = system_value
	o.Threat = threat_value
	o.Traffic = traffic_value
	o.Tunnel = tunnel_value
	o.Url = url_value
	o.Userid = userid_value
	o.Wildfire = wildfire_value

	return diags
}

func (o *EmailServerProfileResourceModel) resourceXpathParentComponents() ([]string, error) {
	var components []string
	return components, nil
}

func (o *EmailServerProfileResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var state EmailServerProfileResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource create", map[string]any{
		"resource_name": "panos_email_server_profile_resource",
		"function":      "Create",
		"name":          state.Name.ValueString(),
	})

	// Verify mode.
	if o.client.Hostname == "" {
		resp.Diagnostics.AddError("Invalid mode error", InspectionModeError)
		return
	}

	var encryptedValues []byte
	ev, err := NewEncryptedValuesManager(encryptedValues, false)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read encrypted values from private state", err.Error())
		return
	}

	// Determine the location.

	var location email.Location

	{
		var terraformLocation EmailServerProfileLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Panorama.IsNull() {
			location.Panorama = &email.PanoramaLocation{}
			var innerLocation EmailServerProfilePanoramaLocation
			resp.Diagnostics.Append(terraformLocation.Panorama.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.Vsys.IsNull() {
			location.Vsys = &email.VsysLocation{}
			var innerLocation EmailServerProfileVsysLocation
			resp.Diagnostics.Append(terraformLocation.Vsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Vsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.Vsys.Vsys = innerLocation.Name.ValueString()
		}

		if !terraformLocation.Template.IsNull() {
			location.Template = &email.TemplateLocation{}
			var innerLocation EmailServerProfileTemplateLocation
			resp.Diagnostics.Append(terraformLocation.Template.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Template.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.Template.Template = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateVsys.IsNull() {
			location.TemplateVsys = &email.TemplateVsysLocation{}
			var innerLocation EmailServerProfileTemplateVsysLocation
			resp.Diagnostics.Append(terraformLocation.TemplateVsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateVsys.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateVsys.Template = innerLocation.Template.ValueString()
			location.TemplateVsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.TemplateVsys.Vsys = innerLocation.Vsys.ValueString()
		}

		if !terraformLocation.TemplateStack.IsNull() {
			location.TemplateStack = &email.TemplateStackLocation{}
			var innerLocation EmailServerProfileTemplateStackLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStack.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStack.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStack.TemplateStack = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateStackVsys.IsNull() {
			location.TemplateStackVsys = &email.TemplateStackVsysLocation{}
			var innerLocation EmailServerProfileTemplateStackVsysLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStackVsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStackVsys.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStackVsys.TemplateStack = innerLocation.TemplateStack.ValueString()
			location.TemplateStackVsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.TemplateStackVsys.Vsys = innerLocation.Vsys.ValueString()
		}
	}

	if err := location.IsValid(); err != nil {
		resp.Diagnostics.AddError("Invalid location", err.Error())
		return
	}

	// Load the desired config.
	var obj *email.Entry
	resp.Diagnostics.Append(state.CopyToPango(ctx, o.client, nil, &obj, ev)...)
	if resp.Diagnostics.HasError() {
		return
	}

	/*
		// Timeout handling.
		ctx, cancel := context.WithTimeout(ctx, GetTimeout(state.Timeouts.Create))
		defer cancel()
	*/

	// Perform the operation.

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}
	created, err := o.manager.Create(ctx, location, components, obj)
	if err != nil {
		resp.Diagnostics.AddError("Error in create", err.Error())
		return
	}

	resp.Diagnostics.Append(state.CopyFromPango(ctx, o.client, nil, created, ev)...)
	if resp.Diagnostics.HasError() {
		return
	}

	payload, err := json.Marshal(ev)
	if err != nil {
		resp.Diagnostics.AddError("Failed to marshal encrypted values state", err.Error())
		return
	}
	resp.Private.SetKey(ctx, "encrypted_values", payload)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (o *EmailServerProfileResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {

	var state EmailServerProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	encryptedValues, diags := req.Private.GetKey(ctx, "encrypted_values")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	ev, err := NewEncryptedValuesManager(encryptedValues, true)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read encrypted values from private state", err.Error())
		return
	}

	var location email.Location

	{
		var terraformLocation EmailServerProfileLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Panorama.IsNull() {
			location.Panorama = &email.PanoramaLocation{}
			var innerLocation EmailServerProfilePanoramaLocation
			resp.Diagnostics.Append(terraformLocation.Panorama.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.Vsys.IsNull() {
			location.Vsys = &email.VsysLocation{}
			var innerLocation EmailServerProfileVsysLocation
			resp.Diagnostics.Append(terraformLocation.Vsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Vsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.Vsys.Vsys = innerLocation.Name.ValueString()
		}

		if !terraformLocation.Template.IsNull() {
			location.Template = &email.TemplateLocation{}
			var innerLocation EmailServerProfileTemplateLocation
			resp.Diagnostics.Append(terraformLocation.Template.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Template.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.Template.Template = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateVsys.IsNull() {
			location.TemplateVsys = &email.TemplateVsysLocation{}
			var innerLocation EmailServerProfileTemplateVsysLocation
			resp.Diagnostics.Append(terraformLocation.TemplateVsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateVsys.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateVsys.Template = innerLocation.Template.ValueString()
			location.TemplateVsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.TemplateVsys.Vsys = innerLocation.Vsys.ValueString()
		}

		if !terraformLocation.TemplateStack.IsNull() {
			location.TemplateStack = &email.TemplateStackLocation{}
			var innerLocation EmailServerProfileTemplateStackLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStack.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStack.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStack.TemplateStack = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateStackVsys.IsNull() {
			location.TemplateStackVsys = &email.TemplateStackVsysLocation{}
			var innerLocation EmailServerProfileTemplateStackVsysLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStackVsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStackVsys.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStackVsys.TemplateStack = innerLocation.TemplateStack.ValueString()
			location.TemplateStackVsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.TemplateStackVsys.Vsys = innerLocation.Vsys.ValueString()
		}
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource read", map[string]any{
		"resource_name": "panos_email_server_profile_resource",
		"function":      "Read",
		"name":          state.Name.ValueString(),
	})

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}
	object, err := o.manager.Read(ctx, location, components, state.Name.ValueString())
	if err != nil {
		if errors.Is(err, sdkmanager.ErrObjectNotFound) {
			resp.State.RemoveResource(ctx)
		} else {
			resp.Diagnostics.AddError("Error reading entry", err.Error())
		}
		return
	}

	copy_diags := state.CopyFromPango(ctx, o.client, nil, object, ev)
	resp.Diagnostics.Append(copy_diags...)

	/*
			// Keep the timeouts.
		    // TODO: This won't work for state import.
			state.Timeouts = state.Timeouts
	*/

	state.Location = state.Location

	payload, err := json.Marshal(ev)
	if err != nil {
		resp.Diagnostics.AddError("Failed to marshal encrypted values state", err.Error())
		return
	}
	resp.Private.SetKey(ctx, "encrypted_values", payload)

	// Done.
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)

}
func (o *EmailServerProfileResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {

	var plan, state EmailServerProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	encryptedValues, diags := req.Private.GetKey(ctx, "encrypted_values")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	ev, err := NewEncryptedValuesManager(encryptedValues, false)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read encrypted values from private state", err.Error())
		return
	}

	var location email.Location

	{
		var terraformLocation EmailServerProfileLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Panorama.IsNull() {
			location.Panorama = &email.PanoramaLocation{}
			var innerLocation EmailServerProfilePanoramaLocation
			resp.Diagnostics.Append(terraformLocation.Panorama.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.Vsys.IsNull() {
			location.Vsys = &email.VsysLocation{}
			var innerLocation EmailServerProfileVsysLocation
			resp.Diagnostics.Append(terraformLocation.Vsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Vsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.Vsys.Vsys = innerLocation.Name.ValueString()
		}

		if !terraformLocation.Template.IsNull() {
			location.Template = &email.TemplateLocation{}
			var innerLocation EmailServerProfileTemplateLocation
			resp.Diagnostics.Append(terraformLocation.Template.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Template.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.Template.Template = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateVsys.IsNull() {
			location.TemplateVsys = &email.TemplateVsysLocation{}
			var innerLocation EmailServerProfileTemplateVsysLocation
			resp.Diagnostics.Append(terraformLocation.TemplateVsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateVsys.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateVsys.Template = innerLocation.Template.ValueString()
			location.TemplateVsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.TemplateVsys.Vsys = innerLocation.Vsys.ValueString()
		}

		if !terraformLocation.TemplateStack.IsNull() {
			location.TemplateStack = &email.TemplateStackLocation{}
			var innerLocation EmailServerProfileTemplateStackLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStack.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStack.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStack.TemplateStack = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateStackVsys.IsNull() {
			location.TemplateStackVsys = &email.TemplateStackVsysLocation{}
			var innerLocation EmailServerProfileTemplateStackVsysLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStackVsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStackVsys.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStackVsys.TemplateStack = innerLocation.TemplateStack.ValueString()
			location.TemplateStackVsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.TemplateStackVsys.Vsys = innerLocation.Vsys.ValueString()
		}
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource update", map[string]any{
		"resource_name": "panos_email_server_profile_resource",
		"function":      "Update",
	})

	// Verify mode.
	if o.client.Hostname == "" {
		resp.Diagnostics.AddError("Invalid mode error", InspectionModeError)
		return
	}

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}
	var obj *email.Entry
	if state.Name.ValueString() != plan.Name.ValueString() {
		obj, err = o.manager.Read(ctx, location, components, state.Name.ValueString())
	} else {
		obj, err = o.manager.Read(ctx, location, components, plan.Name.ValueString())
	}
	if err != nil {
		resp.Diagnostics.AddError("Error in update", err.Error())
		return
	}

	resp.Diagnostics.Append(plan.CopyToPango(ctx, o.client, nil, &obj, ev)...)
	if resp.Diagnostics.HasError() {
		return
	}

	components, err = plan.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}

	// If name differs between plan and state, we need to set old name for the object
	// before calling SDK Update() function to properly handle rename + edit cycle.
	var newName string
	if state.Name.ValueString() != plan.Name.ValueString() {
		newName = plan.Name.ValueString()
		obj.Name = state.Name.ValueString()
	}

	updated, err := o.manager.Update(ctx, location, components, obj, newName)

	if err != nil {
		resp.Diagnostics.AddError("Error in update", err.Error())
		return
	}

	/*
		// Keep the timeouts.
		state.Timeouts = plan.Timeouts
	*/

	copy_diags := plan.CopyFromPango(ctx, o.client, nil, updated, ev)
	resp.Diagnostics.Append(copy_diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	payload, err := json.Marshal(ev)
	if err != nil {
		resp.Diagnostics.AddError("Failed to marshal encrypted values state", err.Error())
		return
	}
	resp.Private.SetKey(ctx, "encrypted_values", payload)

	// Done.
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)

}
func (o *EmailServerProfileResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {

	var state EmailServerProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource delete", map[string]any{
		"resource_name": "panos_email_server_profile_resource",
		"function":      "Delete",
		"name":          state.Name.ValueString(),
	})

	// Verify mode.
	if o.client.Hostname == "" {
		resp.Diagnostics.AddError("Invalid mode error", InspectionModeError)
		return
	}

	var location email.Location

	{
		var terraformLocation EmailServerProfileLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Panorama.IsNull() {
			location.Panorama = &email.PanoramaLocation{}
			var innerLocation EmailServerProfilePanoramaLocation
			resp.Diagnostics.Append(terraformLocation.Panorama.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.Vsys.IsNull() {
			location.Vsys = &email.VsysLocation{}
			var innerLocation EmailServerProfileVsysLocation
			resp.Diagnostics.Append(terraformLocation.Vsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Vsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.Vsys.Vsys = innerLocation.Name.ValueString()
		}

		if !terraformLocation.Template.IsNull() {
			location.Template = &email.TemplateLocation{}
			var innerLocation EmailServerProfileTemplateLocation
			resp.Diagnostics.Append(terraformLocation.Template.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.Template.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.Template.Template = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateVsys.IsNull() {
			location.TemplateVsys = &email.TemplateVsysLocation{}
			var innerLocation EmailServerProfileTemplateVsysLocation
			resp.Diagnostics.Append(terraformLocation.TemplateVsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateVsys.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateVsys.Template = innerLocation.Template.ValueString()
			location.TemplateVsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.TemplateVsys.Vsys = innerLocation.Vsys.ValueString()
		}

		if !terraformLocation.TemplateStack.IsNull() {
			location.TemplateStack = &email.TemplateStackLocation{}
			var innerLocation EmailServerProfileTemplateStackLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStack.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStack.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStack.TemplateStack = innerLocation.Name.ValueString()
		}

		if !terraformLocation.TemplateStackVsys.IsNull() {
			location.TemplateStackVsys = &email.TemplateStackVsysLocation{}
			var innerLocation EmailServerProfileTemplateStackVsysLocation
			resp.Diagnostics.Append(terraformLocation.TemplateStackVsys.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.TemplateStackVsys.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.TemplateStackVsys.TemplateStack = innerLocation.TemplateStack.ValueString()
			location.TemplateStackVsys.NgfwDevice = innerLocation.NgfwDevice.ValueString()
			location.TemplateStackVsys.Vsys = innerLocation.Vsys.ValueString()
		}
	}

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}

	err = o.manager.Delete(ctx, location, components, []string{state.Name.ValueString()})
	if err != nil && !errors.Is(err, sdkmanager.ErrObjectNotFound) {
		resp.Diagnostics.AddError("Error in delete", err.Error())
		return
	}

}

type EmailServerProfileImportState struct {
	Location types.Object `json:"location"`
	Name     types.String `json:"name"`
}

func (o EmailServerProfileImportState) MarshalJSON() ([]byte, error) {
	type shadow struct {
		Location interface{} `json:"location"`
		Name     *string     `json:"name"`
	}
	var location_object interface{}
	{
		var err error
		location_object, err = TypesObjectToMap(o.Location, EmailServerProfileLocationSchema())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal location into JSON document: %w", err)
		}
	}

	obj := shadow{
		Location: location_object,
		Name:     o.Name.ValueStringPointer(),
	}

	return json.Marshal(obj)
}

func (o *EmailServerProfileImportState) UnmarshalJSON(data []byte) error {
	var shadow struct {
		Location interface{} `json:"location"`
		Name     *string     `json:"name"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	var location_object types.Object
	{
		location_map, ok := shadow.Location.(map[string]interface{})
		if !ok {
			return NewDiagnosticsError("Failed to unmarshal JSON document into location: expected map[string]interface{}", nil)
		}
		var err error
		location_object, err = MapToTypesObject(location_map, EmailServerProfileLocationSchema())
		if err != nil {
			return fmt.Errorf("failed to unmarshal location from JSON: %w", err)
		}
	}
	o.Location = location_object
	o.Name = types.StringPointerValue(shadow.Name)

	return nil
}

func EmailServerProfileImportStateCreator(ctx context.Context, resource types.Object) ([]byte, error) {
	attrs := resource.Attributes()
	if attrs == nil {
		return nil, fmt.Errorf("Object has no attributes")
	}

	locationAttr, ok := attrs["location"]
	if !ok {
		return nil, fmt.Errorf("location attribute missing")
	}

	var location types.Object
	switch value := locationAttr.(type) {
	case types.Object:
		location = value
	default:
		return nil, fmt.Errorf("location attribute expected to be an object")
	}
	nameAttr, ok := attrs["name"]
	if !ok {
		return nil, fmt.Errorf("name attribute missing")
	}

	var name types.String
	switch value := nameAttr.(type) {
	case types.String:
		name = value
	default:
		return nil, fmt.Errorf("name attribute expected to be a string")
	}

	importStruct := EmailServerProfileImportState{
		Location: location,
		Name:     name,
	}

	return json.Marshal(importStruct)
}

func (o *EmailServerProfileResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {

	var obj EmailServerProfileImportState
	data, err := base64.StdEncoding.DecodeString(req.ID)
	if err != nil {
		resp.Diagnostics.AddError("Failed to decode Import ID", err.Error())
		return
	}

	err = json.Unmarshal(data, &obj)
	if err != nil {
		var diagsErr *DiagnosticsError
		if errors.As(err, &diagsErr) {
			resp.Diagnostics.Append(diagsErr.Diagnostics()...)
		} else {
			resp.Diagnostics.AddError("Failed to unmarshal Import ID", err.Error())
		}
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("location"), obj.Location)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), obj.Name)...)
}

type EmailServerProfilePanoramaLocation struct {
}
type EmailServerProfileVsysLocation struct {
	NgfwDevice types.String `tfsdk:"ngfw_device"`
	Name       types.String `tfsdk:"name"`
}
type EmailServerProfileTemplateLocation struct {
	PanoramaDevice types.String `tfsdk:"panorama_device"`
	Name           types.String `tfsdk:"name"`
}
type EmailServerProfileTemplateVsysLocation struct {
	PanoramaDevice types.String `tfsdk:"panorama_device"`
	Template       types.String `tfsdk:"template"`
	NgfwDevice     types.String `tfsdk:"ngfw_device"`
	Vsys           types.String `tfsdk:"vsys"`
}
type EmailServerProfileTemplateStackLocation struct {
	PanoramaDevice types.String `tfsdk:"panorama_device"`
	Name           types.String `tfsdk:"name"`
}
type EmailServerProfileTemplateStackVsysLocation struct {
	PanoramaDevice types.String `tfsdk:"panorama_device"`
	TemplateStack  types.String `tfsdk:"template_stack"`
	NgfwDevice     types.String `tfsdk:"ngfw_device"`
	Vsys           types.String `tfsdk:"vsys"`
}
type EmailServerProfileLocation struct {
	Panorama          types.Object `tfsdk:"panorama"`
	Vsys              types.Object `tfsdk:"vsys"`
	Template          types.Object `tfsdk:"template"`
	TemplateVsys      types.Object `tfsdk:"template_vsys"`
	TemplateStack     types.Object `tfsdk:"template_stack"`
	TemplateStackVsys types.Object `tfsdk:"template_stack_vsys"`
}

func EmailServerProfileLocationSchema() rsschema.Attribute {
	return rsschema.SingleNestedAttribute{
		Description: "The location of this object.",
		Required:    true,
		Attributes: map[string]rsschema.Attribute{
			"panorama": rsschema.SingleNestedAttribute{
				Description: "Located in a panorama.",
				Optional:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},

				Validators: []validator.Object{
					objectvalidator.ExactlyOneOf(path.Expressions{
						path.MatchRelative().AtParent().AtName("panorama"),
						path.MatchRelative().AtParent().AtName("vsys"),
						path.MatchRelative().AtParent().AtName("template"),
						path.MatchRelative().AtParent().AtName("template_vsys"),
						path.MatchRelative().AtParent().AtName("template_stack"),
						path.MatchRelative().AtParent().AtName("template_stack_vsys"),
					}...),
				},
			},
			"vsys": rsschema.SingleNestedAttribute{
				Description: "Located in a specific Virtual System",
				Optional:    true,
				Attributes: map[string]rsschema.Attribute{
					"ngfw_device": rsschema.StringAttribute{
						Description: "The NGFW device name",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("localhost.localdomain"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"name": rsschema.StringAttribute{
						Description: "The Virtual System name",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("vsys1"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
				},
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
			},
			"template": rsschema.SingleNestedAttribute{
				Description: "A shared resource located within a specific template",
				Optional:    true,
				Attributes: map[string]rsschema.Attribute{
					"panorama_device": rsschema.StringAttribute{
						Description: "Specific Panorama device",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("localhost.localdomain"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"name": rsschema.StringAttribute{
						Description: "Specific Panorama template",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString(""),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
				},
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
			},
			"template_vsys": rsschema.SingleNestedAttribute{
				Description: "Located in a specific template, device and vsys.",
				Optional:    true,
				Attributes: map[string]rsschema.Attribute{
					"panorama_device": rsschema.StringAttribute{
						Description: "Specific Panorama device",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("localhost.localdomain"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"template": rsschema.StringAttribute{
						Description: "Specific Panorama template",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString(""),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"ngfw_device": rsschema.StringAttribute{
						Description: "The NGFW device",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("localhost.localdomain"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"vsys": rsschema.StringAttribute{
						Description: "The vsys.",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("vsys1"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
				},
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
			},
			"template_stack": rsschema.SingleNestedAttribute{
				Description: "Located in a specific template stack",
				Optional:    true,
				Attributes: map[string]rsschema.Attribute{
					"panorama_device": rsschema.StringAttribute{
						Description: "Specific Panorama device",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("localhost.localdomain"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"name": rsschema.StringAttribute{
						Description: "The template stack",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString(""),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
				},
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
			},
			"template_stack_vsys": rsschema.SingleNestedAttribute{
				Description: "Located in a specific template stack, device and vsys.",
				Optional:    true,
				Attributes: map[string]rsschema.Attribute{
					"panorama_device": rsschema.StringAttribute{
						Description: "Specific Panorama device",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("localhost.localdomain"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"template_stack": rsschema.StringAttribute{
						Description: "The template stack",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString(""),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"ngfw_device": rsschema.StringAttribute{
						Description: "The NGFW device",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("localhost.localdomain"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"vsys": rsschema.StringAttribute{
						Description: "The vsys.",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("vsys1"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
				},
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}

func (o EmailServerProfilePanoramaLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
	}

	obj := shadow{}

	return json.Marshal(obj)
}

func (o *EmailServerProfilePanoramaLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}

	return nil
}
func (o EmailServerProfileVsysLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
		NgfwDevice *string `json:"ngfw_device,omitempty"`
		Name       *string `json:"name,omitempty"`
	}

	obj := shadow{
		NgfwDevice: o.NgfwDevice.ValueStringPointer(),
		Name:       o.Name.ValueStringPointer(),
	}

	return json.Marshal(obj)
}

func (o *EmailServerProfileVsysLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
		NgfwDevice *string `json:"ngfw_device,omitempty"`
		Name       *string `json:"name,omitempty"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	o.NgfwDevice = types.StringPointerValue(shadow.NgfwDevice)
	o.Name = types.StringPointerValue(shadow.Name)

	return nil
}
func (o EmailServerProfileTemplateLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		Name           *string `json:"name,omitempty"`
	}

	obj := shadow{
		PanoramaDevice: o.PanoramaDevice.ValueStringPointer(),
		Name:           o.Name.ValueStringPointer(),
	}

	return json.Marshal(obj)
}

func (o *EmailServerProfileTemplateLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		Name           *string `json:"name,omitempty"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	o.PanoramaDevice = types.StringPointerValue(shadow.PanoramaDevice)
	o.Name = types.StringPointerValue(shadow.Name)

	return nil
}
func (o EmailServerProfileTemplateVsysLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		Template       *string `json:"template,omitempty"`
		NgfwDevice     *string `json:"ngfw_device,omitempty"`
		Vsys           *string `json:"vsys,omitempty"`
	}

	obj := shadow{
		PanoramaDevice: o.PanoramaDevice.ValueStringPointer(),
		Template:       o.Template.ValueStringPointer(),
		NgfwDevice:     o.NgfwDevice.ValueStringPointer(),
		Vsys:           o.Vsys.ValueStringPointer(),
	}

	return json.Marshal(obj)
}

func (o *EmailServerProfileTemplateVsysLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		Template       *string `json:"template,omitempty"`
		NgfwDevice     *string `json:"ngfw_device,omitempty"`
		Vsys           *string `json:"vsys,omitempty"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	o.PanoramaDevice = types.StringPointerValue(shadow.PanoramaDevice)
	o.Template = types.StringPointerValue(shadow.Template)
	o.NgfwDevice = types.StringPointerValue(shadow.NgfwDevice)
	o.Vsys = types.StringPointerValue(shadow.Vsys)

	return nil
}
func (o EmailServerProfileTemplateStackLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		Name           *string `json:"name,omitempty"`
	}

	obj := shadow{
		PanoramaDevice: o.PanoramaDevice.ValueStringPointer(),
		Name:           o.Name.ValueStringPointer(),
	}

	return json.Marshal(obj)
}

func (o *EmailServerProfileTemplateStackLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		Name           *string `json:"name,omitempty"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	o.PanoramaDevice = types.StringPointerValue(shadow.PanoramaDevice)
	o.Name = types.StringPointerValue(shadow.Name)

	return nil
}
func (o EmailServerProfileTemplateStackVsysLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		TemplateStack  *string `json:"template_stack,omitempty"`
		NgfwDevice     *string `json:"ngfw_device,omitempty"`
		Vsys           *string `json:"vsys,omitempty"`
	}

	obj := shadow{
		PanoramaDevice: o.PanoramaDevice.ValueStringPointer(),
		TemplateStack:  o.TemplateStack.ValueStringPointer(),
		NgfwDevice:     o.NgfwDevice.ValueStringPointer(),
		Vsys:           o.Vsys.ValueStringPointer(),
	}

	return json.Marshal(obj)
}

func (o *EmailServerProfileTemplateStackVsysLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		TemplateStack  *string `json:"template_stack,omitempty"`
		NgfwDevice     *string `json:"ngfw_device,omitempty"`
		Vsys           *string `json:"vsys,omitempty"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	o.PanoramaDevice = types.StringPointerValue(shadow.PanoramaDevice)
	o.TemplateStack = types.StringPointerValue(shadow.TemplateStack)
	o.NgfwDevice = types.StringPointerValue(shadow.NgfwDevice)
	o.Vsys = types.StringPointerValue(shadow.Vsys)

	return nil
}
func (o EmailServerProfileLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
		Panorama          *EmailServerProfilePanoramaLocation          `json:"panorama,omitempty"`
		Vsys              *EmailServerProfileVsysLocation              `json:"vsys,omitempty"`
		Template          *EmailServerProfileTemplateLocation          `json:"template,omitempty"`
		TemplateVsys      *EmailServerProfileTemplateVsysLocation      `json:"template_vsys,omitempty"`
		TemplateStack     *EmailServerProfileTemplateStackLocation     `json:"template_stack,omitempty"`
		TemplateStackVsys *EmailServerProfileTemplateStackVsysLocation `json:"template_stack_vsys,omitempty"`
	}
	var panorama_object *EmailServerProfilePanoramaLocation
	{
		diags := o.Panorama.As(context.TODO(), &panorama_object, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			return nil, NewDiagnosticsError("Failed to marshal panorama into JSON document", diags.Errors())
		}
	}
	var vsys_object *EmailServerProfileVsysLocation
	{
		diags := o.Vsys.As(context.TODO(), &vsys_object, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			return nil, NewDiagnosticsError("Failed to marshal vsys into JSON document", diags.Errors())
		}
	}
	var template_object *EmailServerProfileTemplateLocation
	{
		diags := o.Template.As(context.TODO(), &template_object, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			return nil, NewDiagnosticsError("Failed to marshal template into JSON document", diags.Errors())
		}
	}
	var templateVsys_object *EmailServerProfileTemplateVsysLocation
	{
		diags := o.TemplateVsys.As(context.TODO(), &templateVsys_object, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			return nil, NewDiagnosticsError("Failed to marshal template_vsys into JSON document", diags.Errors())
		}
	}
	var templateStack_object *EmailServerProfileTemplateStackLocation
	{
		diags := o.TemplateStack.As(context.TODO(), &templateStack_object, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			return nil, NewDiagnosticsError("Failed to marshal template_stack into JSON document", diags.Errors())
		}
	}
	var templateStackVsys_object *EmailServerProfileTemplateStackVsysLocation
	{
		diags := o.TemplateStackVsys.As(context.TODO(), &templateStackVsys_object, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			return nil, NewDiagnosticsError("Failed to marshal template_stack_vsys into JSON document", diags.Errors())
		}
	}

	obj := shadow{
		Panorama:          panorama_object,
		Vsys:              vsys_object,
		Template:          template_object,
		TemplateVsys:      templateVsys_object,
		TemplateStack:     templateStack_object,
		TemplateStackVsys: templateStackVsys_object,
	}

	return json.Marshal(obj)
}

func (o *EmailServerProfileLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
		Panorama          *EmailServerProfilePanoramaLocation          `json:"panorama,omitempty"`
		Vsys              *EmailServerProfileVsysLocation              `json:"vsys,omitempty"`
		Template          *EmailServerProfileTemplateLocation          `json:"template,omitempty"`
		TemplateVsys      *EmailServerProfileTemplateVsysLocation      `json:"template_vsys,omitempty"`
		TemplateStack     *EmailServerProfileTemplateStackLocation     `json:"template_stack,omitempty"`
		TemplateStackVsys *EmailServerProfileTemplateStackVsysLocation `json:"template_stack_vsys,omitempty"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	var panorama_object types.Object
	{
		var diags_tmp diag.Diagnostics
		panorama_object, diags_tmp = types.ObjectValueFrom(context.TODO(), shadow.Panorama.AttributeTypes(), shadow.Panorama)
		if diags_tmp.HasError() {
			return NewDiagnosticsError("Failed to unmarshal JSON document into panorama", diags_tmp.Errors())
		}
	}
	var vsys_object types.Object
	{
		var diags_tmp diag.Diagnostics
		vsys_object, diags_tmp = types.ObjectValueFrom(context.TODO(), shadow.Vsys.AttributeTypes(), shadow.Vsys)
		if diags_tmp.HasError() {
			return NewDiagnosticsError("Failed to unmarshal JSON document into vsys", diags_tmp.Errors())
		}
	}
	var template_object types.Object
	{
		var diags_tmp diag.Diagnostics
		template_object, diags_tmp = types.ObjectValueFrom(context.TODO(), shadow.Template.AttributeTypes(), shadow.Template)
		if diags_tmp.HasError() {
			return NewDiagnosticsError("Failed to unmarshal JSON document into template", diags_tmp.Errors())
		}
	}
	var templateVsys_object types.Object
	{
		var diags_tmp diag.Diagnostics
		templateVsys_object, diags_tmp = types.ObjectValueFrom(context.TODO(), shadow.TemplateVsys.AttributeTypes(), shadow.TemplateVsys)
		if diags_tmp.HasError() {
			return NewDiagnosticsError("Failed to unmarshal JSON document into template_vsys", diags_tmp.Errors())
		}
	}
	var templateStack_object types.Object
	{
		var diags_tmp diag.Diagnostics
		templateStack_object, diags_tmp = types.ObjectValueFrom(context.TODO(), shadow.TemplateStack.AttributeTypes(), shadow.TemplateStack)
		if diags_tmp.HasError() {
			return NewDiagnosticsError("Failed to unmarshal JSON document into template_stack", diags_tmp.Errors())
		}
	}
	var templateStackVsys_object types.Object
	{
		var diags_tmp diag.Diagnostics
		templateStackVsys_object, diags_tmp = types.ObjectValueFrom(context.TODO(), shadow.TemplateStackVsys.AttributeTypes(), shadow.TemplateStackVsys)
		if diags_tmp.HasError() {
			return NewDiagnosticsError("Failed to unmarshal JSON document into template_stack_vsys", diags_tmp.Errors())
		}
	}
	o.Panorama = panorama_object
	o.Vsys = vsys_object
	o.Template = template_object
	o.TemplateVsys = templateVsys_object
	o.TemplateStack = templateStack_object
	o.TemplateStackVsys = templateStackVsys_object

	return nil
}

func (o *EmailServerProfilePanoramaLocation) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{}
}
func (o *EmailServerProfileVsysLocation) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"ngfw_device": types.StringType,
		"name":        types.StringType,
	}
}
func (o *EmailServerProfileTemplateLocation) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"panorama_device": types.StringType,
		"name":            types.StringType,
	}
}
func (o *EmailServerProfileTemplateVsysLocation) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"panorama_device": types.StringType,
		"template":        types.StringType,
		"ngfw_device":     types.StringType,
		"vsys":            types.StringType,
	}
}
func (o *EmailServerProfileTemplateStackLocation) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"panorama_device": types.StringType,
		"name":            types.StringType,
	}
}
func (o *EmailServerProfileTemplateStackVsysLocation) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"panorama_device": types.StringType,
		"template_stack":  types.StringType,
		"ngfw_device":     types.StringType,
		"vsys":            types.StringType,
	}
}
func (o *EmailServerProfileLocation) AttributeTypes() map[string]attr.Type {
	var panoramaObj EmailServerProfilePanoramaLocation
	var vsysObj EmailServerProfileVsysLocation
	var templateObj EmailServerProfileTemplateLocation
	var templateVsysObj EmailServerProfileTemplateVsysLocation
	var templateStackObj EmailServerProfileTemplateStackLocation
	var templateStackVsysObj EmailServerProfileTemplateStackVsysLocation
	return map[string]attr.Type{
		"panorama": types.ObjectType{
			AttrTypes: panoramaObj.AttributeTypes(),
		},
		"vsys": types.ObjectType{
			AttrTypes: vsysObj.AttributeTypes(),
		},
		"template": types.ObjectType{
			AttrTypes: templateObj.AttributeTypes(),
		},
		"template_vsys": types.ObjectType{
			AttrTypes: templateVsysObj.AttributeTypes(),
		},
		"template_stack": types.ObjectType{
			AttrTypes: templateStackObj.AttributeTypes(),
		},
		"template_stack_vsys": types.ObjectType{
			AttrTypes: templateStackVsysObj.AttributeTypes(),
		},
	}
}
